/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddProccessRequest {
    #[serde(rename = "processName", skip_serializing_if = "Option::is_none")]
    pub process_name: Option<String>,
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(rename = "executionPath", skip_serializing_if = "Option::is_none")]
    pub execution_path: Option<String>,
    #[serde(rename = "processPriority", skip_serializing_if = "Option::is_none")]
    pub process_priority: Option<crate::models::ProcessPriorityEnum>,
    #[serde(rename = "affinity", skip_serializing_if = "Option::is_none")]
    pub affinity: Option<Vec<i32>>,
    #[serde(rename = "profileId", skip_serializing_if = "Option::is_none")]
    pub profile_id: Option<i32>,
}

impl AddProccessRequest {
    pub fn new() -> AddProccessRequest {
        AddProccessRequest {
            process_name: None,
            alias: None,
            execution_path: None,
            process_priority: None,
            affinity: None,
            profile_id: None,
        }
    }
}


