/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddProccessRequest {
    #[serde(rename = "processName")]
    pub process_name: String,
    #[serde(rename = "alias")]
    pub alias: String,
    #[serde(rename = "executionPath")]
    pub execution_path: String,
    #[serde(rename = "processPriority")]
    pub process_priority: crate::models::ProcessPriorityEnum,
    #[serde(rename = "affinity")]
    pub affinity: Vec<i32>,
    #[serde(rename = "profileId")]
    pub profile_id: i32,
}

impl AddProccessRequest {
    pub fn new(process_name: String, alias: String, execution_path: String, process_priority: crate::models::ProcessPriorityEnum, affinity: Vec<i32>, profile_id: i32) -> AddProccessRequest {
        AddProccessRequest {
            process_name,
            alias,
            execution_path,
            process_priority,
            affinity,
            profile_id,
        }
    }
}


