/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientSettings {
    #[serde(rename = "alwaysOnTop")]
    pub always_on_top: bool,
}

impl ClientSettings {
    pub fn new(always_on_top: bool) -> ClientSettings {
        ClientSettings {
            always_on_top,
        }
    }
}


