/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ClientSettings {
    #[serde(rename = "alwaysOnTop", skip_serializing_if = "Option::is_none")]
    pub always_on_top: Option<bool>,
}

impl ClientSettings {
    pub fn new() -> ClientSettings {
        ClientSettings {
            always_on_top: None,
        }
    }
}


