/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CpuUsages {
    #[serde(rename = "coreClocksMhz", skip_serializing_if = "Option::is_none")]
    pub core_clocks_mhz: Option<Vec<f32>>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<f32>,
    #[serde(rename = "powerDrawWattage", skip_serializing_if = "Option::is_none")]
    pub power_draw_wattage: Option<f32>,
    #[serde(rename = "cores", skip_serializing_if = "Option::is_none")]
    pub cores: Option<Vec<f32>>,
    #[serde(rename = "temperatureReadings", skip_serializing_if = "Option::is_none")]
    pub temperature_readings: Option<::std::collections::HashMap<String, f32>>,
}

impl CpuUsages {
    pub fn new() -> CpuUsages {
        CpuUsages {
            core_clocks_mhz: None,
            total: None,
            power_draw_wattage: None,
            cores: None,
            temperature_readings: None,
        }
    }
}


