/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CpuCache {
    #[serde(rename = "l1Size", skip_serializing_if = "Option::is_none")]
    pub l1_size: Option<i64>,
    #[serde(rename = "l1LineSize", skip_serializing_if = "Option::is_none")]
    pub l1_line_size: Option<i64>,
    #[serde(rename = "l2Size", skip_serializing_if = "Option::is_none")]
    pub l2_size: Option<i64>,
    #[serde(rename = "l2LineSize", skip_serializing_if = "Option::is_none")]
    pub l2_line_size: Option<i64>,
    #[serde(rename = "l3Size", skip_serializing_if = "Option::is_none")]
    pub l3_size: Option<i64>,
    #[serde(rename = "l3LineSize", skip_serializing_if = "Option::is_none")]
    pub l3_line_size: Option<i64>,
}

impl CpuCache {
    pub fn new() -> CpuCache {
        CpuCache {
            l1_size: None,
            l1_line_size: None,
            l2_size: None,
            l2_line_size: None,
            l3_size: None,
            l3_line_size: None,
        }
    }
}


