/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CpuUsageMetricModel {
    #[serde(rename = "totalCoreUsagePercentage", skip_serializing_if = "Option::is_none")]
    pub total_core_usage_percentage: Option<f32>,
    #[serde(rename = "packageTemperature", skip_serializing_if = "Option::is_none")]
    pub package_temperature: Option<f32>,
    #[serde(rename = "powerDrawWattage", skip_serializing_if = "Option::is_none")]
    pub power_draw_wattage: Option<f32>,
    #[serde(rename = "coreClocksMhz", skip_serializing_if = "Option::is_none")]
    pub core_clocks_mhz: Option<::std::collections::HashMap<String, f32>>,
    #[serde(rename = "coresUsagePercentage", skip_serializing_if = "Option::is_none")]
    pub cores_usage_percentage: Option<::std::collections::HashMap<String, f32>>,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "uniqueIdentifier", skip_serializing_if = "Option::is_none")]
    pub unique_identifier: Option<String>,
}

impl CpuUsageMetricModel {
    pub fn new(id: i32) -> CpuUsageMetricModel {
        CpuUsageMetricModel {
            total_core_usage_percentage: None,
            package_temperature: None,
            power_draw_wattage: None,
            core_clocks_mhz: None,
            cores_usage_percentage: None,
            id,
            unique_identifier: None,
        }
    }
}


