/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateProfileRequest {
    #[serde(rename = "name")]
    pub name: String,
}

impl CreateProfileRequest {
    pub fn new(name: String) -> CreateProfileRequest {
        CreateProfileRequest {
            name,
        }
    }
}


