/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Data {
    #[serde(rename = "dataReadBytes", skip_serializing_if = "Option::is_none")]
    pub data_read_bytes: Option<i64>,
    #[serde(rename = "dataWrittenBytes", skip_serializing_if = "Option::is_none")]
    pub data_written_bytes: Option<i64>,
}

impl Data {
    pub fn new() -> Data {
        Data {
            data_read_bytes: None,
            data_written_bytes: None,
        }
    }
}


