/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DateRange {
    #[serde(rename = "earliest", skip_serializing_if = "Option::is_none")]
    pub earliest: Option<String>,
    #[serde(rename = "latest", skip_serializing_if = "Option::is_none")]
    pub latest: Option<String>,
}

impl DateRange {
    pub fn new() -> DateRange {
        DateRange {
            earliest: None,
            latest: None,
        }
    }
}


