/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DiskHealth {
    #[serde(rename = "totalBytesRead", skip_serializing_if = "Option::is_none")]
    pub total_bytes_read: Option<f32>,
    #[serde(rename = "totalBytesWritten", skip_serializing_if = "Option::is_none")]
    pub total_bytes_written: Option<f32>,
}

impl DiskHealth {
    pub fn new() -> DiskHealth {
        DiskHealth {
            total_bytes_read: None,
            total_bytes_written: None,
        }
    }
}


