/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DiskType {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "HDD")]
    Hdd,
    #[serde(rename = "SSD")]
    Ssd,

}

impl ToString for DiskType {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("Unknown"),
            Self::Hdd => String::from("HDD"),
            Self::Ssd => String::from("SSD"),
        }
    }
}

impl Default for DiskType {
    fn default() -> DiskType {
        Self::Unknown
    }
}




