/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Disk {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "serial", skip_serializing_if = "Option::is_none")]
    pub serial: Option<String>,
    #[serde(rename = "letter", skip_serializing_if = "Option::is_none")]
    pub letter: Option<String>,
    #[serde(rename = "diskType", skip_serializing_if = "Option::is_none")]
    pub disk_type: Option<crate::models::DiskType>,
    #[serde(rename = "throughput", skip_serializing_if = "Option::is_none")]
    pub throughput: Option<Box<crate::models::DiskThroughput>>,
    #[serde(rename = "load", skip_serializing_if = "Option::is_none")]
    pub load: Option<Box<crate::models::DiskLoad>>,
    #[serde(rename = "temperatures", skip_serializing_if = "Option::is_none")]
    pub temperatures: Option<::std::collections::HashMap<String, f32>>,
    #[serde(rename = "health", skip_serializing_if = "Option::is_none")]
    pub health: Option<Box<crate::models::DiskHealth>>,
}

impl Disk {
    pub fn new() -> Disk {
        Disk {
            name: None,
            serial: None,
            letter: None,
            disk_type: None,
            throughput: None,
            load: None,
            temperatures: None,
            health: None,
        }
    }
}


