/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiskLoad {
    #[serde(rename = "usedSpacePercentage", skip_serializing_if = "Option::is_none")]
    pub used_space_percentage: Option<f32>,
    #[serde(rename = "usedSpaceBytes", skip_serializing_if = "Option::is_none")]
    pub used_space_bytes: Option<i64>,
    #[serde(rename = "totalFreeSpaceBytes", skip_serializing_if = "Option::is_none")]
    pub total_free_space_bytes: Option<i64>,
    #[serde(rename = "writeActivityPercentage", skip_serializing_if = "Option::is_none")]
    pub write_activity_percentage: Option<f32>,
    #[serde(rename = "totalActivityPercentage", skip_serializing_if = "Option::is_none")]
    pub total_activity_percentage: Option<f32>,
}

impl DiskLoad {
    pub fn new() -> DiskLoad {
        DiskLoad {
            used_space_percentage: None,
            used_space_bytes: None,
            total_free_space_bytes: None,
            write_activity_percentage: None,
            total_activity_percentage: None,
        }
    }
}


