/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetMachineDynamicDataResponse {
    #[serde(rename = "cpuUsageData")]
    pub cpu_usage_data: Box<crate::models::CpuUsages>,
    #[serde(rename = "ramUsagesData")]
    pub ram_usages_data: Box<crate::models::RamUsages>,
    #[serde(rename = "gpuUsageData")]
    pub gpu_usage_data: Option<Vec<crate::models::GpuUsages>>,
    #[serde(rename = "diskUsages")]
    pub disk_usages: Box<crate::models::DiskUsages>,
    #[serde(rename = "networkUsageData")]
    pub network_usage_data: Box<crate::models::NetworkAdapters>,
    #[serde(rename = "processCpuUsage")]
    pub process_cpu_usage: Option<::std::collections::HashMap<String, f32>>,
    #[serde(rename = "processCpuThreadsUsage")]
    pub process_cpu_threads_usage: Option<::std::collections::HashMap<String, f32>>,
    #[serde(rename = "processThreadCount")]
    pub process_thread_count: Option<::std::collections::HashMap<String, f32>>,
    #[serde(rename = "processRamUsageGb")]
    pub process_ram_usage_gb: Option<::std::collections::HashMap<String, f32>>,
    #[serde(rename = "processDiskBytesPerSecActivity")]
    pub process_disk_bytes_per_sec_activity: Option<::std::collections::HashMap<String, f64>>,
    #[serde(rename = "cpuTemperature")]
    pub cpu_temperature: Option<::std::collections::HashMap<String, f32>>,
    #[serde(rename = "processGpuUsage")]
    pub process_gpu_usage: Option<::std::collections::HashMap<String, f32>>,
}

impl GetMachineDynamicDataResponse {
    pub fn new(cpu_usage_data: crate::models::CpuUsages, ram_usages_data: crate::models::RamUsages, gpu_usage_data: Option<Vec<crate::models::GpuUsages>>, disk_usages: crate::models::DiskUsages, network_usage_data: crate::models::NetworkAdapters, process_cpu_usage: Option<::std::collections::HashMap<String, f32>>, process_cpu_threads_usage: Option<::std::collections::HashMap<String, f32>>, process_thread_count: Option<::std::collections::HashMap<String, f32>>, process_ram_usage_gb: Option<::std::collections::HashMap<String, f32>>, process_disk_bytes_per_sec_activity: Option<::std::collections::HashMap<String, f64>>, cpu_temperature: Option<::std::collections::HashMap<String, f32>>, process_gpu_usage: Option<::std::collections::HashMap<String, f32>>) -> GetMachineDynamicDataResponse {
        GetMachineDynamicDataResponse {
            cpu_usage_data: Box::new(cpu_usage_data),
            ram_usages_data: Box::new(ram_usages_data),
            gpu_usage_data,
            disk_usages: Box::new(disk_usages),
            network_usage_data: Box::new(network_usage_data),
            process_cpu_usage,
            process_cpu_threads_usage,
            process_thread_count,
            process_ram_usage_gb,
            process_disk_bytes_per_sec_activity,
            cpu_temperature,
            process_gpu_usage,
        }
    }
}


