/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMachineTimeSeriesRequest {
    #[serde(rename = "earliest")]
    pub earliest: String,
    #[serde(rename = "latest")]
    pub latest: String,
}

impl GetMachineTimeSeriesRequest {
    pub fn new(earliest: String, latest: String) -> GetMachineTimeSeriesRequest {
        GetMachineTimeSeriesRequest {
            earliest,
            latest,
        }
    }
}


