/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetManagedResponse {
    #[serde(rename = "affinityModels", skip_serializing_if = "Option::is_none")]
    pub affinity_models: Option<Vec<crate::models::ManagedModelDto>>,
}

impl GetManagedResponse {
    pub fn new() -> GetManagedResponse {
        GetManagedResponse {
            affinity_models: None,
        }
    }
}


