/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetManagedResponse {
    #[serde(rename = "affinityModels")]
    pub affinity_models: Vec<crate::models::ManagedModelDto>,
}

impl GetManagedResponse {
    pub fn new(affinity_models: Vec<crate::models::ManagedModelDto>) -> GetManagedResponse {
        GetManagedResponse {
            affinity_models,
        }
    }
}


