/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetRunningProcessesResponse {
    #[serde(rename = "processView", skip_serializing_if = "Option::is_none")]
    pub process_view: Option<::std::collections::HashMap<String, crate::models::ParentChildModelDto>>,
}

impl GetRunningProcessesResponse {
    pub fn new() -> GetRunningProcessesResponse {
        GetRunningProcessesResponse {
            process_view: None,
        }
    }
}


