/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAllResponse {
    #[serde(rename = "managedModels", skip_serializing_if = "Option::is_none")]
    pub managed_models: Option<Vec<crate::models::ManagedModelDto>>,
    #[serde(rename = "processesToAdd", skip_serializing_if = "Option::is_none")]
    pub processes_to_add: Option<Vec<crate::models::ProcessToAddDto>>,
}

impl GetAllResponse {
    pub fn new() -> GetAllResponse {
        GetAllResponse {
            managed_models: None,
            processes_to_add: None,
        }
    }
}


