/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GpuClockSpeeds {
    #[serde(rename = "memoryClockMhz", skip_serializing_if = "Option::is_none")]
    pub memory_clock_mhz: Option<i32>,
    #[serde(rename = "computeClockMhz", skip_serializing_if = "Option::is_none")]
    pub compute_clock_mhz: Option<i32>,
    #[serde(rename = "graphicsClockMhz", skip_serializing_if = "Option::is_none")]
    pub graphics_clock_mhz: Option<i32>,
    #[serde(rename = "videoClockMhz", skip_serializing_if = "Option::is_none")]
    pub video_clock_mhz: Option<i32>,
}

impl GpuClockSpeeds {
    pub fn new() -> GpuClockSpeeds {
        GpuClockSpeeds {
            memory_clock_mhz: None,
            compute_clock_mhz: None,
            graphics_clock_mhz: None,
            video_clock_mhz: None,
        }
    }
}


