/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GpuData {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "memoryTotalBytes", skip_serializing_if = "Option::is_none")]
    pub memory_total_bytes: Option<f32>,
}

impl GpuData {
    pub fn new() -> GpuData {
        GpuData {
            name: None,
            memory_total_bytes: None,
        }
    }
}


