/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GpuData {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "memoryTotalBytes")]
    pub memory_total_bytes: Option<f32>,
}

impl GpuData {
    pub fn new(name: String, memory_total_bytes: Option<f32>) -> GpuData {
        GpuData {
            name,
            memory_total_bytes,
        }
    }
}


