/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GpuUsage {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "temperatureReadings")]
    pub temperature_readings: ::std::collections::HashMap<String, f32>,
    #[serde(rename = "deviceIndex")]
    pub device_index: i32,
    #[serde(rename = "partNumber", skip_serializing_if = "Option::is_none")]
    pub part_number: Option<String>,
    #[serde(rename = "totalMemoryBytes", skip_serializing_if = "Option::is_none")]
    pub total_memory_bytes: Option<i64>,
    #[serde(rename = "memoryUsedBytes", skip_serializing_if = "Option::is_none")]
    pub memory_used_bytes: Option<i64>,
    #[serde(rename = "clockSpeeds", skip_serializing_if = "Option::is_none")]
    pub clock_speeds: Option<Box<crate::models::GpuClockSpeeds>>,
    #[serde(rename = "fanPercentage", skip_serializing_if = "Option::is_none")]
    pub fan_percentage: Option<::std::collections::HashMap<String, f32>>,
    #[serde(rename = "powerDrawWatt", skip_serializing_if = "Option::is_none")]
    pub power_draw_watt: Option<i32>,
    #[serde(rename = "load", skip_serializing_if = "Option::is_none")]
    pub load: Option<Box<crate::models::LoadData>>,
    #[serde(rename = "pcIe", skip_serializing_if = "Option::is_none")]
    pub pc_ie: Option<Box<crate::models::PcieThroughPut>>,
}

impl GpuUsage {
    pub fn new(temperature_readings: ::std::collections::HashMap<String, f32>, device_index: i32) -> GpuUsage {
        GpuUsage {
            name: None,
            temperature_readings,
            device_index,
            part_number: None,
            total_memory_bytes: None,
            memory_used_bytes: None,
            clock_speeds: None,
            fan_percentage: None,
            power_draw_watt: None,
            load: None,
            pc_ie: None,
        }
    }
}


