/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GpuUsageMetricModel {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "uniqueIdentifier")]
    pub unique_identifier: Option<String>,
    #[serde(rename = "coreUsagePercentage")]
    pub core_usage_percentage: Option<f32>,
    #[serde(rename = "vramUsageBytes")]
    pub vram_usage_bytes: Option<f32>,
    #[serde(rename = "vramTotalBytes")]
    pub vram_total_bytes: Option<f32>,
    #[serde(rename = "coreTemperature")]
    pub core_temperature: Option<f32>,
    #[serde(rename = "powerDrawWattage")]
    pub power_draw_wattage: Option<f32>,
    #[serde(rename = "fanPercentage")]
    pub fan_percentage: Option<::std::collections::HashMap<String, f32>>,
}

impl GpuUsageMetricModel {
    pub fn new(id: i32, unique_identifier: Option<String>, core_usage_percentage: Option<f32>, vram_usage_bytes: Option<f32>, vram_total_bytes: Option<f32>, core_temperature: Option<f32>, power_draw_wattage: Option<f32>, fan_percentage: Option<::std::collections::HashMap<String, f32>>) -> GpuUsageMetricModel {
        GpuUsageMetricModel {
            id,
            unique_identifier,
            core_usage_percentage,
            vram_usage_bytes,
            vram_total_bytes,
            core_temperature,
            power_draw_wattage,
            fan_percentage,
        }
    }
}


