/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InfluxDbSettings {
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "reportIntervalSeconds")]
    pub report_interval_seconds: i32,
    #[serde(rename = "endPoint")]
    pub end_point: String,
    #[serde(rename = "token")]
    pub token: String,
}

impl InfluxDbSettings {
    pub fn new(enabled: bool, report_interval_seconds: i32, end_point: String, token: String) -> InfluxDbSettings {
        InfluxDbSettings {
            enabled,
            report_interval_seconds,
            end_point,
            token,
        }
    }
}


