/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InfluxDbSettings {
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "reportIntervalSeconds", skip_serializing_if = "Option::is_none")]
    pub report_interval_seconds: Option<i32>,
    #[serde(rename = "endPoint", skip_serializing_if = "Option::is_none")]
    pub end_point: Option<String>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

impl InfluxDbSettings {
    pub fn new() -> InfluxDbSettings {
        InfluxDbSettings {
            enabled: None,
            report_interval_seconds: None,
            end_point: None,
            token: None,
        }
    }
}


