/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IpInterfaceProperties {
    #[serde(rename = "iPv4Address")]
    pub i_pv4_address: Option<String>,
    #[serde(rename = "iPv6Address")]
    pub i_pv6_address: Option<String>,
    #[serde(rename = "dnsSuffix")]
    pub dns_suffix: Option<String>,
    #[serde(rename = "isDnsEnabled")]
    pub is_dns_enabled: bool,
}

impl IpInterfaceProperties {
    pub fn new(i_pv4_address: Option<String>, i_pv6_address: Option<String>, dns_suffix: Option<String>, is_dns_enabled: bool) -> IpInterfaceProperties {
        IpInterfaceProperties {
            i_pv4_address,
            i_pv6_address,
            dns_suffix,
            is_dns_enabled,
        }
    }
}


