/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LaunchSettings {
    #[serde(rename = "vitalServiceHttpsPort")]
    pub vital_service_https_port: i32,
    #[serde(rename = "vitalServiceHttpPort")]
    pub vital_service_http_port: i32,
}

impl LaunchSettings {
    pub fn new(vital_service_https_port: i32, vital_service_http_port: i32) -> LaunchSettings {
        LaunchSettings {
            vital_service_https_port,
            vital_service_http_port,
        }
    }
}


