/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LaunchSettings {
    #[serde(rename = "vitalServiceHttpsPort", skip_serializing_if = "Option::is_none")]
    pub vital_service_https_port: Option<i32>,
    #[serde(rename = "vitalServiceHttpPort", skip_serializing_if = "Option::is_none")]
    pub vital_service_http_port: Option<i32>,
}

impl LaunchSettings {
    pub fn new() -> LaunchSettings {
        LaunchSettings {
            vital_service_https_port: None,
            vital_service_http_port: None,
        }
    }
}


