/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LoadData {
    #[serde(rename = "corePercentage", skip_serializing_if = "Option::is_none")]
    pub core_percentage: Option<f32>,
    #[serde(rename = "frameBufferPercentage", skip_serializing_if = "Option::is_none")]
    pub frame_buffer_percentage: Option<f32>,
    #[serde(rename = "videoEnginePercentage", skip_serializing_if = "Option::is_none")]
    pub video_engine_percentage: Option<f32>,
    #[serde(rename = "busInterfacePercentage", skip_serializing_if = "Option::is_none")]
    pub bus_interface_percentage: Option<f32>,
    #[serde(rename = "memoryUsedPercentage", skip_serializing_if = "Option::is_none")]
    pub memory_used_percentage: Option<f32>,
    #[serde(rename = "memoryControllerPercentage", skip_serializing_if = "Option::is_none")]
    pub memory_controller_percentage: Option<f32>,
    #[serde(rename = "cudaPercentage", skip_serializing_if = "Option::is_none")]
    pub cuda_percentage: Option<f32>,
    #[serde(rename = "threeDPercentage", skip_serializing_if = "Option::is_none")]
    pub three_d_percentage: Option<f32>,
}

impl LoadData {
    pub fn new() -> LoadData {
        LoadData {
            core_percentage: None,
            frame_buffer_percentage: None,
            video_engine_percentage: None,
            bus_interface_percentage: None,
            memory_used_percentage: None,
            memory_controller_percentage: None,
            cuda_percentage: None,
            three_d_percentage: None,
        }
    }
}


