/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ManagedModelDto {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "processName", skip_serializing_if = "Option::is_none")]
    pub process_name: Option<String>,
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(rename = "processPriority", skip_serializing_if = "Option::is_none")]
    pub process_priority: Option<crate::models::ProcessPriorityEnum>,
    #[serde(rename = "affinity", skip_serializing_if = "Option::is_none")]
    pub affinity: Option<Vec<i32>>,
    #[serde(rename = "parentProfileId", skip_serializing_if = "Option::is_none")]
    pub parent_profile_id: Option<i32>,
}

impl ManagedModelDto {
    pub fn new() -> ManagedModelDto {
        ManagedModelDto {
            id: None,
            process_name: None,
            alias: None,
            process_priority: None,
            affinity: None,
            parent_profile_id: None,
        }
    }
}


