/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricsSettings {
    #[serde(rename = "persistMetrics", skip_serializing_if = "Option::is_none")]
    pub persist_metrics: Option<bool>,
}

impl MetricsSettings {
    pub fn new() -> MetricsSettings {
        MetricsSettings {
            persist_metrics: None,
        }
    }
}


