/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NetAdapterUsage {
    #[serde(rename = "uploadSpeedBps")]
    pub upload_speed_bps: i64,
    #[serde(rename = "downloadSpeedBps")]
    pub download_speed_bps: i64,
    #[serde(rename = "uploadedBps")]
    pub uploaded_bps: i64,
    #[serde(rename = "downloadedBps")]
    pub downloaded_bps: i64,
    #[serde(rename = "usagePercentage")]
    pub usage_percentage: i64,
}

impl NetAdapterUsage {
    pub fn new(upload_speed_bps: i64, download_speed_bps: i64, uploaded_bps: i64, downloaded_bps: i64, usage_percentage: i64) -> NetAdapterUsage {
        NetAdapterUsage {
            upload_speed_bps,
            download_speed_bps,
            uploaded_bps,
            downloaded_bps,
            usage_percentage,
        }
    }
}


