/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NetAdapterUsage {
    #[serde(rename = "sendBps")]
    pub send_bps: i64,
    #[serde(rename = "recieveBps")]
    pub recieve_bps: i64,
    #[serde(rename = "sentBytes")]
    pub sent_bytes: i64,
    #[serde(rename = "recievedBytes")]
    pub recieved_bytes: i64,
    #[serde(rename = "usagePercentage", skip_serializing_if = "Option::is_none")]
    pub usage_percentage: Option<f32>,
}

impl NetAdapterUsage {
    pub fn new(send_bps: i64, recieve_bps: i64, sent_bytes: i64, recieved_bytes: i64) -> NetAdapterUsage {
        NetAdapterUsage {
            send_bps,
            recieve_bps,
            sent_bytes,
            recieved_bytes,
            usage_percentage: None,
        }
    }
}


