/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NetworkUsageMetricModel {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "uniqueIdentifier")]
    pub unique_identifier: Option<String>,
    #[serde(rename = "uploadSpeedBps")]
    pub upload_speed_bps: Option<i64>,
    #[serde(rename = "downloadSpeedBps")]
    pub download_speed_bps: Option<i64>,
}

impl NetworkUsageMetricModel {
    pub fn new(id: i32, unique_identifier: Option<String>, upload_speed_bps: Option<i64>, download_speed_bps: Option<i64>) -> NetworkUsageMetricModel {
        NetworkUsageMetricModel {
            id,
            unique_identifier,
            upload_speed_bps,
            download_speed_bps,
        }
    }
}


