/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NetworkAdapterUtil {
    #[serde(rename = "sendBps", skip_serializing_if = "Option::is_none")]
    pub send_bps: Option<f32>,
    #[serde(rename = "recieveBps", skip_serializing_if = "Option::is_none")]
    pub recieve_bps: Option<f32>,
}

impl NetworkAdapterUtil {
    pub fn new() -> NetworkAdapterUtil {
        NetworkAdapterUtil {
            send_bps: None,
            recieve_bps: None,
        }
    }
}


