/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NetworkAdapterProperties {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "macAddress", skip_serializing_if = "Option::is_none")]
    pub mac_address: Option<String>,
    #[serde(rename = "speedBps", skip_serializing_if = "Option::is_none")]
    pub speed_bps: Option<f32>,
    #[serde(rename = "connectionType", skip_serializing_if = "Option::is_none")]
    pub connection_type: Option<String>,
    #[serde(rename = "iPv4Address", skip_serializing_if = "Option::is_none")]
    pub i_pv4_address: Option<Vec<String>>,
    #[serde(rename = "iPv6Address", skip_serializing_if = "Option::is_none")]
    pub i_pv6_address: Option<Vec<String>>,
    #[serde(rename = "dnsSuffix", skip_serializing_if = "Option::is_none")]
    pub dns_suffix: Option<String>,
}

impl NetworkAdapterProperties {
    pub fn new() -> NetworkAdapterProperties {
        NetworkAdapterProperties {
            name: None,
            description: None,
            mac_address: None,
            speed_bps: None,
            connection_type: None,
            i_pv4_address: None,
            i_pv6_address: None,
            dns_suffix: None,
        }
    }
}


