/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NetworkAdapterProperties {
    #[serde(rename = "ipInterfaceProperties", skip_serializing_if = "Option::is_none")]
    pub ip_interface_properties: Option<Box<crate::models::IpInterfaceProperties>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "macAddress")]
    pub mac_address: String,
    #[serde(rename = "speedBps", skip_serializing_if = "Option::is_none")]
    pub speed_bps: Option<i64>,
    #[serde(rename = "connectionType", skip_serializing_if = "Option::is_none")]
    pub connection_type: Option<String>,
}

impl NetworkAdapterProperties {
    pub fn new(name: String, mac_address: String) -> NetworkAdapterProperties {
        NetworkAdapterProperties {
            ip_interface_properties: None,
            name,
            description: None,
            mac_address,
            speed_bps: None,
            connection_type: None,
        }
    }
}


