/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessGpuUtil {
    #[serde(rename = "gpuCorePercentage", skip_serializing_if = "Option::is_none")]
    pub gpu_core_percentage: Option<f32>,
    #[serde(rename = "gpuMemPercentage", skip_serializing_if = "Option::is_none")]
    pub gpu_mem_percentage: Option<f32>,
    #[serde(rename = "gpuEncodingPercentage", skip_serializing_if = "Option::is_none")]
    pub gpu_encoding_percentage: Option<f32>,
    #[serde(rename = "gpuDecodingPercentage", skip_serializing_if = "Option::is_none")]
    pub gpu_decoding_percentage: Option<f32>,
}

impl ProcessGpuUtil {
    pub fn new() -> ProcessGpuUtil {
        ProcessGpuUtil {
            gpu_core_percentage: None,
            gpu_mem_percentage: None,
            gpu_encoding_percentage: None,
            gpu_decoding_percentage: None,
        }
    }
}


