/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProcessData {
    #[serde(rename = "pid")]
    pub pid: f32,
    #[serde(rename = "parentPid")]
    pub parent_pid: Option<f32>,
    #[serde(rename = "executablePath")]
    pub executable_path: Option<String>,
    #[serde(rename = "description")]
    pub description: Option<String>,
    #[serde(rename = "mainWindowTitle")]
    pub main_window_title: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "timeStamp")]
    pub time_stamp: String,
    #[serde(rename = "cpuPercentage")]
    pub cpu_percentage: f32,
    #[serde(rename = "memoryKb")]
    pub memory_kb: f32,
    #[serde(rename = "diskUsage")]
    pub disk_usage: Box<crate::models::ProcessDiskUsage>,
    #[serde(rename = "status")]
    pub status: Option<String>,
    #[serde(rename = "gpuUtil")]
    pub gpu_util: Box<crate::models::ProcessGpuUtil>,
}

impl ProcessData {
    pub fn new(pid: f32, parent_pid: Option<f32>, executable_path: Option<String>, description: Option<String>, main_window_title: Option<String>, name: String, time_stamp: String, cpu_percentage: f32, memory_kb: f32, disk_usage: crate::models::ProcessDiskUsage, status: Option<String>, gpu_util: crate::models::ProcessGpuUtil) -> ProcessData {
        ProcessData {
            pid,
            parent_pid,
            executable_path,
            description,
            main_window_title,
            name,
            time_stamp,
            cpu_percentage,
            memory_kb,
            disk_usage: Box::new(disk_usage),
            status,
            gpu_util: Box::new(gpu_util),
        }
    }
}


