/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProcessGpuUtil {
    #[serde(rename = "gpuCorePercentage")]
    pub gpu_core_percentage: Option<f32>,
    #[serde(rename = "gpuMemPercentage")]
    pub gpu_mem_percentage: Option<f32>,
    #[serde(rename = "gpuEncodingPercentage")]
    pub gpu_encoding_percentage: Option<f32>,
    #[serde(rename = "gpuDecodingPercentage")]
    pub gpu_decoding_percentage: Option<f32>,
}

impl ProcessGpuUtil {
    pub fn new(gpu_core_percentage: Option<f32>, gpu_mem_percentage: Option<f32>, gpu_encoding_percentage: Option<f32>, gpu_decoding_percentage: Option<f32>) -> ProcessGpuUtil {
        ProcessGpuUtil {
            gpu_core_percentage,
            gpu_mem_percentage,
            gpu_encoding_percentage,
            gpu_decoding_percentage,
        }
    }
}


