/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProcessViewDto {
    #[serde(rename = "processName")]
    pub process_name: String,
    #[serde(rename = "processTitle")]
    pub process_title: Option<String>,
    #[serde(rename = "description")]
    pub description: Option<String>,
    #[serde(rename = "id")]
    pub id: i32,
}

impl ProcessViewDto {
    pub fn new(process_name: String, process_title: Option<String>, description: Option<String>, id: i32) -> ProcessViewDto {
        ProcessViewDto {
            process_name,
            process_title,
            description,
            id,
        }
    }
}


