/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProcessViewDto {
    #[serde(rename = "processName")]
    pub process_name: String,
    #[serde(rename = "processTitle", skip_serializing_if = "Option::is_none")]
    pub process_title: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "id")]
    pub id: i32,
}

impl ProcessViewDto {
    pub fn new(process_name: String, id: i32) -> ProcessViewDto {
        ProcessViewDto {
            process_name,
            process_title: None,
            description: None,
            id,
        }
    }
}


