/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProcessDiskUsage {
    #[serde(rename = "readBytesPerSecond", skip_serializing_if = "Option::is_none")]
    pub read_bytes_per_second: Option<f32>,
    #[serde(rename = "writeBytesPerSecond", skip_serializing_if = "Option::is_none")]
    pub write_bytes_per_second: Option<f32>,
}

impl ProcessDiskUsage {
    pub fn new() -> ProcessDiskUsage {
        ProcessDiskUsage {
            read_bytes_per_second: None,
            write_bytes_per_second: None,
        }
    }
}


