/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProcessToAddDto {
    #[serde(rename = "pid", skip_serializing_if = "Option::is_none")]
    pub pid: Option<i32>,
    #[serde(rename = "processName", skip_serializing_if = "Option::is_none")]
    pub process_name: Option<String>,
    #[serde(rename = "mainWindowTitle", skip_serializing_if = "Option::is_none")]
    pub main_window_title: Option<String>,
    #[serde(rename = "executionPath", skip_serializing_if = "Option::is_none")]
    pub execution_path: Option<String>,
    #[serde(rename = "canModify", skip_serializing_if = "Option::is_none")]
    pub can_modify: Option<bool>,
    #[serde(rename = "affinity", skip_serializing_if = "Option::is_none")]
    pub affinity: Option<Vec<i32>>,
    #[serde(rename = "processPriority", skip_serializing_if = "Option::is_none")]
    pub process_priority: Option<crate::models::ProcessPriorityEnum>,
}

impl ProcessToAddDto {
    pub fn new() -> ProcessToAddDto {
        ProcessToAddDto {
            pid: None,
            process_name: None,
            main_window_title: None,
            execution_path: None,
            can_modify: None,
            affinity: None,
            process_priority: None,
        }
    }
}


