/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileDto {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "managedModelsIds")]
    pub managed_models_ids: Vec<i32>,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "active")]
    pub active: bool,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
}

impl ProfileDto {
    pub fn new(id: i32, name: String, managed_models_ids: Vec<i32>, enabled: bool, active: bool) -> ProfileDto {
        ProfileDto {
            id,
            name,
            managed_models_ids,
            enabled,
            active,
            priority: None,
        }
    }
}


