/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RamData {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "partNumber", skip_serializing_if = "Option::is_none")]
    pub part_number: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "speedMhz", skip_serializing_if = "Option::is_none")]
    pub speed_mhz: Option<i32>,
    #[serde(rename = "slotNumber", skip_serializing_if = "Option::is_none")]
    pub slot_number: Option<i32>,
    #[serde(rename = "slotChannel", skip_serializing_if = "Option::is_none")]
    pub slot_channel: Option<String>,
    #[serde(rename = "configuredClockSpeedMhz", skip_serializing_if = "Option::is_none")]
    pub configured_clock_speed_mhz: Option<i32>,
    #[serde(rename = "capacity", skip_serializing_if = "Option::is_none")]
    pub capacity: Option<f64>,
}

impl RamData {
    pub fn new() -> RamData {
        RamData {
            name: None,
            part_number: None,
            r#type: None,
            speed_mhz: None,
            slot_number: None,
            slot_channel: None,
            configured_clock_speed_mhz: None,
            capacity: None,
        }
    }
}


