/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RamUsageMetricModel {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "uniqueIdentifier")]
    pub unique_identifier: Option<String>,
    #[serde(rename = "usedMemoryBytes")]
    pub used_memory_bytes: Option<f64>,
    #[serde(rename = "totalVisibleMemoryBytes")]
    pub total_visible_memory_bytes: Option<f64>,
}

impl RamUsageMetricModel {
    pub fn new(id: i32, unique_identifier: Option<String>, used_memory_bytes: Option<f64>, total_visible_memory_bytes: Option<f64>) -> RamUsageMetricModel {
        RamUsageMetricModel {
            id,
            unique_identifier,
            used_memory_bytes,
            total_visible_memory_bytes,
        }
    }
}


