/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RamData {
    #[serde(rename = "name")]
    pub name: Option<String>,
    #[serde(rename = "partNumber")]
    pub part_number: Option<String>,
    #[serde(rename = "type")]
    pub _type: Option<String>,
    #[serde(rename = "speedMhz")]
    pub speed_mhz: Option<i32>,
    #[serde(rename = "slotNumber")]
    pub slot_number: Option<i32>,
    #[serde(rename = "slotChannel")]
    pub slot_channel: Option<String>,
    #[serde(rename = "configuredClockSpeedMhz")]
    pub configured_clock_speed_mhz: Option<i32>,
    #[serde(rename = "capacity")]
    pub capacity: Option<f64>,
}

impl RamData {
    pub fn new(name: Option<String>, part_number: Option<String>, _type: Option<String>, speed_mhz: Option<i32>, slot_number: Option<i32>, slot_channel: Option<String>, configured_clock_speed_mhz: Option<i32>, capacity: Option<f64>) -> RamData {
        RamData {
            name,
            part_number,
            _type,
            speed_mhz,
            slot_number,
            slot_channel,
            configured_clock_speed_mhz,
            capacity,
        }
    }
}


