/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendUtilizationRequest {
    #[serde(rename = "processData")]
    pub process_data: Vec<crate::models::ProcessData>,
    #[serde(rename = "systemUsage")]
    pub system_usage: Box<crate::models::SystemUsage>,
}

impl SendUtilizationRequest {
    pub fn new(process_data: Vec<crate::models::ProcessData>, system_usage: crate::models::SystemUsage) -> SendUtilizationRequest {
        SendUtilizationRequest {
            process_data,
            system_usage: Box::new(system_usage),
        }
    }
}


