/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SettingsDto {
    #[serde(rename = "runAtStarup", skip_serializing_if = "Option::is_none")]
    pub run_at_starup: Option<bool>,
    #[serde(rename = "launch")]
    pub launch: Box<crate::models::LaunchSettings>,
    #[serde(rename = "metrics")]
    pub metrics: Box<crate::models::MetricsSettings>,
    #[serde(rename = "influxDb")]
    pub influx_db: Box<crate::models::InfluxDbSettings>,
}

impl SettingsDto {
    pub fn new(launch: crate::models::LaunchSettings, metrics: crate::models::MetricsSettings, influx_db: crate::models::InfluxDbSettings) -> SettingsDto {
        SettingsDto {
            run_at_starup: None,
            launch: Box::new(launch),
            metrics: Box::new(metrics),
            influx_db: Box::new(influx_db),
        }
    }
}


