/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SettingsDto {
    #[serde(rename = "runAtStarup", skip_serializing_if = "Option::is_none")]
    pub run_at_starup: Option<bool>,
    #[serde(rename = "launch", skip_serializing_if = "Option::is_none")]
    pub launch: Option<Box<crate::models::LaunchSettings>>,
    #[serde(rename = "metrics", skip_serializing_if = "Option::is_none")]
    pub metrics: Option<Box<crate::models::MetricsSettings>>,
    #[serde(rename = "influxDb", skip_serializing_if = "Option::is_none")]
    pub influx_db: Option<Box<crate::models::InfluxDbSettings>>,
}

impl SettingsDto {
    pub fn new() -> SettingsDto {
        SettingsDto {
            run_at_starup: None,
            launch: None,
            metrics: None,
            influx_db: None,
        }
    }
}


