/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemUsage {
    #[serde(rename = "cpuUsage")]
    pub cpu_usage: Box<crate::models::CpuUsage>,
    #[serde(rename = "memUsage")]
    pub mem_usage: Box<crate::models::MemoryUsage>,
    #[serde(rename = "gpuUsage")]
    pub gpu_usage: Vec<crate::models::GpuUsage>,
    #[serde(rename = "networkAdapterUsage")]
    pub network_adapter_usage: Vec<crate::models::NetworkAdapterUsage>,
    #[serde(rename = "diskUsage")]
    pub disk_usage: ::std::collections::HashMap<String, crate::models::DiskUsage>,
}

impl SystemUsage {
    pub fn new(cpu_usage: crate::models::CpuUsage, mem_usage: crate::models::MemoryUsage, gpu_usage: Vec<crate::models::GpuUsage>, network_adapter_usage: Vec<crate::models::NetworkAdapterUsage>, disk_usage: ::std::collections::HashMap<String, crate::models::DiskUsage>) -> SystemUsage {
        SystemUsage {
            cpu_usage: Box::new(cpu_usage),
            mem_usage: Box::new(mem_usage),
            gpu_usage,
            network_adapter_usage,
            disk_usage,
        }
    }
}


