/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SystemUsage {
    #[serde(rename = "cpuUsage", skip_serializing_if = "Option::is_none")]
    pub cpu_usage: Option<Box<crate::models::CpuUsage>>,
    #[serde(rename = "memUsage", skip_serializing_if = "Option::is_none")]
    pub mem_usage: Option<Box<crate::models::MemUsage>>,
    #[serde(rename = "networkAdapterUsage", skip_serializing_if = "Option::is_none")]
    pub network_adapter_usage: Option<Vec<crate::models::NetworkAdapterUsage>>,
    #[serde(rename = "disk", skip_serializing_if = "Option::is_none")]
    pub disk: Option<::std::collections::HashMap<String, crate::models::Disk>>,
}

impl SystemUsage {
    pub fn new() -> SystemUsage {
        SystemUsage {
            cpu_usage: None,
            mem_usage: None,
            network_adapter_usage: None,
            disk: None,
        }
    }
}


