/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Throughput {
    #[serde(rename = "readRateBytesPerSecond")]
    pub read_rate_bytes_per_second: Option<i64>,
    #[serde(rename = "writeRateBytesPerSecond")]
    pub write_rate_bytes_per_second: Option<i64>,
}

impl Throughput {
    pub fn new(read_rate_bytes_per_second: Option<i64>, write_rate_bytes_per_second: Option<i64>) -> Throughput {
        Throughput {
            read_rate_bytes_per_second,
            write_rate_bytes_per_second,
        }
    }
}


