/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TimeSeriesMachineMetricsResponse {
    #[serde(rename = "requestRange", skip_serializing_if = "Option::is_none")]
    pub request_range: Option<Box<crate::models::DateRange>>,
    #[serde(rename = "metrics", skip_serializing_if = "Option::is_none")]
    pub metrics: Option<Vec<crate::models::TimeSeriesMachineMetricsModel>>,
}

impl TimeSeriesMachineMetricsResponse {
    pub fn new() -> TimeSeriesMachineMetricsResponse {
        TimeSeriesMachineMetricsResponse {
            request_range: None,
            metrics: None,
        }
    }
}


