/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TimeSeriesMachineMetricsModel {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "dateTimeOffset")]
    pub date_time_offset: String,
    #[serde(rename = "cpuUsageData")]
    pub cpu_usage_data: Vec<crate::models::CpuUsageMetricModel>,
    #[serde(rename = "gpuUsageData")]
    pub gpu_usage_data: Vec<crate::models::GpuUsageMetricModel>,
    #[serde(rename = "ramUsageData")]
    pub ram_usage_data: Box<crate::models::RamUsageMetricModel>,
    #[serde(rename = "networkUsageData")]
    pub network_usage_data: Vec<crate::models::NetworkUsageMetricModel>,
    #[serde(rename = "diskUsageData")]
    pub disk_usage_data: Vec<crate::models::DiskUsageMetricModel>,
}

impl TimeSeriesMachineMetricsModel {
    pub fn new(id: i32, date_time_offset: String, cpu_usage_data: Vec<crate::models::CpuUsageMetricModel>, gpu_usage_data: Vec<crate::models::GpuUsageMetricModel>, ram_usage_data: crate::models::RamUsageMetricModel, network_usage_data: Vec<crate::models::NetworkUsageMetricModel>, disk_usage_data: Vec<crate::models::DiskUsageMetricModel>) -> TimeSeriesMachineMetricsModel {
        TimeSeriesMachineMetricsModel {
            id,
            date_time_offset,
            cpu_usage_data,
            gpu_usage_data,
            ram_usage_data: Box::new(ram_usage_data),
            network_usage_data,
            disk_usage_data,
        }
    }
}


