/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProfileRequest {
    #[serde(rename = "profile")]
    pub profile: Box<crate::models::ProfileDto>,
}

impl UpdateProfileRequest {
    pub fn new(profile: crate::models::ProfileDto) -> UpdateProfileRequest {
        UpdateProfileRequest {
            profile: Box::new(profile),
        }
    }
}


