/*
 * VitalService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateManagedRequest {
    #[serde(rename = "managedModelDto", skip_serializing_if = "Option::is_none")]
    pub managed_model_dto: Option<Box<crate::models::ManagedModelDto>>,
}

impl UpdateManagedRequest {
    pub fn new() -> UpdateManagedRequest {
        UpdateManagedRequest {
            managed_model_dto: None,
        }
    }
}


