name: Improvement
description: Suggest an improvement for an existing feature
title: "improvement "
labels: ["Improvement"]
body:
  - type: textarea
    id: improvement
    attributes:
      label: "What improvement would you like to see?"
      description: "What is the issue you're having with the current feature"
      placeholder: "It would be awesome if...."
      value: "It would be awesome if"
    validations:
      required: true
