/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SendUtilizationRequest,
} from '../models';
import {
    SendUtilizationRequestFromJSON,
    SendUtilizationRequestToJSON,
} from '../models';

export interface ApiIngestUtilizationPostRequest {
    sendUtilizationRequest?: SendUtilizationRequest;
}

/**
 * 
 */
export class IngestApi extends runtime.BaseAPI {

    /**
     */
    async apiIngestUtilizationPostRaw(requestParameters: ApiIngestUtilizationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Ingest/Utilization`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendUtilizationRequestToJSON(requestParameters.sendUtilizationRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiIngestUtilizationPost(requestParameters: ApiIngestUtilizationPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiIngestUtilizationPostRaw(requestParameters, initOverrides);
    }

}
