/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddProccessRequest,
  CreateProfileRequest,
  ProfileDto,
  UpdateManagedRequest,
  UpdateProfileRequest,
} from '../models';
import {
    AddProccessRequestFromJSON,
    AddProccessRequestToJSON,
    CreateProfileRequestFromJSON,
    CreateProfileRequestToJSON,
    ProfileDtoFromJSON,
    ProfileDtoToJSON,
    UpdateManagedRequestFromJSON,
    UpdateManagedRequestToJSON,
    UpdateProfileRequestFromJSON,
    UpdateProfileRequestToJSON,
} from '../models';

export interface ApiProfileAddProcessConfigPutRequest {
    addProccessRequest?: AddProccessRequest;
}

export interface ApiProfileCreatePutRequest {
    createProfileRequest?: CreateProfileRequest;
}

export interface ApiProfileDeleteProcessConfigIdDeleteRequest {
    id: number;
}

export interface ApiProfileIdDeleteRequest {
    id: number;
}

export interface ApiProfileIdGetRequest {
    id: number;
}

export interface ApiProfileUpdateProcessConfigPutRequest {
    updateManagedRequest?: UpdateManagedRequest;
}

export interface ApiProfileUpdatePutRequest {
    updateProfileRequest?: UpdateProfileRequest;
}

/**
 * 
 */
export class ProfileApi extends runtime.BaseAPI {

    /**
     */
    async apiProfileAddProcessConfigPutRaw(requestParameters: ApiProfileAddProcessConfigPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Profile/AddProcessConfig`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AddProccessRequestToJSON(requestParameters.addProccessRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiProfileAddProcessConfigPut(requestParameters: ApiProfileAddProcessConfigPutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiProfileAddProcessConfigPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiProfileCreatePutRaw(requestParameters: ApiProfileCreatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProfileDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Profile/Create`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProfileRequestToJSON(requestParameters.createProfileRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiProfileCreatePut(requestParameters: ApiProfileCreatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProfileDto> {
        const response = await this.apiProfileCreatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiProfileDeleteProcessConfigIdDeleteRaw(requestParameters: ApiProfileDeleteProcessConfigIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiProfileDeleteProcessConfigIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Profile/DeleteProcessConfig/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiProfileDeleteProcessConfigIdDelete(requestParameters: ApiProfileDeleteProcessConfigIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiProfileDeleteProcessConfigIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiProfileGetAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProfileDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Profile/GetAll`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProfileDtoFromJSON));
    }

    /**
     */
    async apiProfileGetAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProfileDto>> {
        const response = await this.apiProfileGetAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiProfileIdDeleteRaw(requestParameters: ApiProfileIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiProfileIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Profile/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiProfileIdDelete(requestParameters: ApiProfileIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiProfileIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiProfileIdGetRaw(requestParameters: ApiProfileIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProfileDto>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiProfileIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Profile/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiProfileIdGet(requestParameters: ApiProfileIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProfileDto> {
        const response = await this.apiProfileIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiProfileUpdateProcessConfigPutRaw(requestParameters: ApiProfileUpdateProcessConfigPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Profile/UpdateProcessConfig`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateManagedRequestToJSON(requestParameters.updateManagedRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiProfileUpdateProcessConfigPut(requestParameters: ApiProfileUpdateProcessConfigPutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiProfileUpdateProcessConfigPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiProfileUpdatePutRaw(requestParameters: ApiProfileUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Profile/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProfileRequestToJSON(requestParameters.updateProfileRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiProfileUpdatePut(requestParameters: ApiProfileUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiProfileUpdatePutRaw(requestParameters, initOverrides);
    }

}
