/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetMachineDynamicDataResponse,
  GetMachineStaticDataResponse,
  GetMachineTimeSeriesRequest,
  TimeSeriesMachineMetricsResponse,
} from '../models';
import {
    GetMachineDynamicDataResponseFromJSON,
    GetMachineDynamicDataResponseToJSON,
    GetMachineStaticDataResponseFromJSON,
    GetMachineStaticDataResponseToJSON,
    GetMachineTimeSeriesRequestFromJSON,
    GetMachineTimeSeriesRequestToJSON,
    TimeSeriesMachineMetricsResponseFromJSON,
    TimeSeriesMachineMetricsResponseToJSON,
} from '../models';

export interface ApiSystemTimeseriesPostRequest {
    getMachineTimeSeriesRequest?: GetMachineTimeSeriesRequest;
}

/**
 * 
 */
export class SystemApi extends runtime.BaseAPI {

    /**
     */
    async apiSystemDynamicGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetMachineDynamicDataResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/System/dynamic`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetMachineDynamicDataResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiSystemDynamicGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetMachineDynamicDataResponse> {
        const response = await this.apiSystemDynamicGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiSystemStaticGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetMachineStaticDataResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/System/static`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetMachineStaticDataResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiSystemStaticGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetMachineStaticDataResponse> {
        const response = await this.apiSystemStaticGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiSystemTimeseriesPostRaw(requestParameters: ApiSystemTimeseriesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSeriesMachineMetricsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/System/timeseries`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetMachineTimeSeriesRequestToJSON(requestParameters.getMachineTimeSeriesRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSeriesMachineMetricsResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiSystemTimeseriesPost(requestParameters: ApiSystemTimeseriesPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSeriesMachineMetricsResponse> {
        const response = await this.apiSystemTimeseriesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
