[debug]
address = "127.0.0.1"
port = 6769
workers = 2
log = "normal"
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 6769
workers = 2
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 6769
workers = 2
log = "critical"
limits = { forms = 32768 }