/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CpuData
 */
export interface CpuData {
    /**
     * 
     * @type {string}
     * @memberof CpuData
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CpuData
     */
    numberOfEnabledCore?: number;
    /**
     * 
     * @type {number}
     * @memberof CpuData
     */
    numberOfCores?: number;
    /**
     * 
     * @type {number}
     * @memberof CpuData
     */
    threadCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CpuData
     */
    virtualizationFirmwareEnabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CpuData
     */
    l1CacheSize?: number;
    /**
     * 
     * @type {number}
     * @memberof CpuData
     */
    l2CacheSize?: number;
    /**
     * 
     * @type {number}
     * @memberof CpuData
     */
    l3CacheSize?: number;
}

/**
 * Check if a given object implements the CpuData interface.
 */
export function instanceOfCpuData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CpuDataFromJSON(json: any): CpuData {
    return CpuDataFromJSONTyped(json, false);
}

export function CpuDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CpuData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'numberOfEnabledCore': !exists(json, 'numberOfEnabledCore') ? undefined : json['numberOfEnabledCore'],
        'numberOfCores': !exists(json, 'numberOfCores') ? undefined : json['numberOfCores'],
        'threadCount': !exists(json, 'threadCount') ? undefined : json['threadCount'],
        'virtualizationFirmwareEnabled': !exists(json, 'virtualizationFirmwareEnabled') ? undefined : json['virtualizationFirmwareEnabled'],
        'l1CacheSize': !exists(json, 'l1CacheSize') ? undefined : json['l1CacheSize'],
        'l2CacheSize': !exists(json, 'l2CacheSize') ? undefined : json['l2CacheSize'],
        'l3CacheSize': !exists(json, 'l3CacheSize') ? undefined : json['l3CacheSize'],
    };
}

export function CpuDataToJSON(value?: CpuData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'numberOfEnabledCore': value.numberOfEnabledCore,
        'numberOfCores': value.numberOfCores,
        'threadCount': value.threadCount,
        'virtualizationFirmwareEnabled': value.virtualizationFirmwareEnabled,
        'l1CacheSize': value.l1CacheSize,
        'l2CacheSize': value.l2CacheSize,
        'l3CacheSize': value.l3CacheSize,
    };
}

