/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CpuUsage
 */
export interface CpuUsage {
    /**
     * 
     * @type {Array<number>}
     * @memberof CpuUsage
     */
    coreClocksMhz: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof CpuUsage
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof CpuUsage
     */
    powerDrawWattage: number | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof CpuUsage
     */
    corePercentages: Array<number>;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof CpuUsage
     */
    temperatureReadings: { [key: string]: number; };
}

/**
 * Check if a given object implements the CpuUsage interface.
 */
export function instanceOfCpuUsage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "coreClocksMhz" in value;
    isInstance = isInstance && "total" in value;
    isInstance = isInstance && "powerDrawWattage" in value;
    isInstance = isInstance && "corePercentages" in value;
    isInstance = isInstance && "temperatureReadings" in value;

    return isInstance;
}

export function CpuUsageFromJSON(json: any): CpuUsage {
    return CpuUsageFromJSONTyped(json, false);
}

export function CpuUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CpuUsage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'coreClocksMhz': json['coreClocksMhz'],
        'total': json['total'],
        'powerDrawWattage': json['powerDrawWattage'],
        'corePercentages': json['corePercentages'],
        'temperatureReadings': json['temperatureReadings'],
    };
}

export function CpuUsageToJSON(value?: CpuUsage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'coreClocksMhz': value.coreClocksMhz,
        'total': value.total,
        'powerDrawWattage': value.powerDrawWattage,
        'corePercentages': value.corePercentages,
        'temperatureReadings': value.temperatureReadings,
    };
}

