/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DriveType } from './DriveType';
import {
    DriveTypeFromJSON,
    DriveTypeFromJSONTyped,
    DriveTypeToJSON,
} from './DriveType';

/**
 * 
 * @export
 * @interface DiskUsageMetricModel
 */
export interface DiskUsageMetricModel {
    /**
     * 
     * @type {number}
     * @memberof DiskUsageMetricModel
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof DiskUsageMetricModel
     */
    uniqueIdentifier: string | null;
    /**
     * 
     * @type {string}
     * @memberof DiskUsageMetricModel
     */
    serial: string | null;
    /**
     * 
     * @type {string}
     * @memberof DiskUsageMetricModel
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof DiskUsageMetricModel
     */
    driveLetter: string | null;
    /**
     * 
     * @type {DriveType}
     * @memberof DiskUsageMetricModel
     */
    driveType: DriveType;
    /**
     * 
     * @type {number}
     * @memberof DiskUsageMetricModel
     */
    usedSpacePercentage: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiskUsageMetricModel
     */
    usedSpaceBytes: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiskUsageMetricModel
     */
    writeActivityPercentage: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiskUsageMetricModel
     */
    totalActivityPercentage: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiskUsageMetricModel
     */
    readRateBytesPerSecond: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiskUsageMetricModel
     */
    writeRateBytesPerSecond: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiskUsageMetricModel
     */
    dataReadBytes: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiskUsageMetricModel
     */
    dataWrittenBytes: number | null;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof DiskUsageMetricModel
     */
    temperatures: { [key: string]: number; } | null;
}

/**
 * Check if a given object implements the DiskUsageMetricModel interface.
 */
export function instanceOfDiskUsageMetricModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "uniqueIdentifier" in value;
    isInstance = isInstance && "serial" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "driveLetter" in value;
    isInstance = isInstance && "driveType" in value;
    isInstance = isInstance && "usedSpacePercentage" in value;
    isInstance = isInstance && "usedSpaceBytes" in value;
    isInstance = isInstance && "writeActivityPercentage" in value;
    isInstance = isInstance && "totalActivityPercentage" in value;
    isInstance = isInstance && "readRateBytesPerSecond" in value;
    isInstance = isInstance && "writeRateBytesPerSecond" in value;
    isInstance = isInstance && "dataReadBytes" in value;
    isInstance = isInstance && "dataWrittenBytes" in value;
    isInstance = isInstance && "temperatures" in value;

    return isInstance;
}

export function DiskUsageMetricModelFromJSON(json: any): DiskUsageMetricModel {
    return DiskUsageMetricModelFromJSONTyped(json, false);
}

export function DiskUsageMetricModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiskUsageMetricModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'uniqueIdentifier': json['uniqueIdentifier'],
        'serial': json['serial'],
        'name': json['name'],
        'driveLetter': json['driveLetter'],
        'driveType': DriveTypeFromJSON(json['driveType']),
        'usedSpacePercentage': json['usedSpacePercentage'],
        'usedSpaceBytes': json['usedSpaceBytes'],
        'writeActivityPercentage': json['writeActivityPercentage'],
        'totalActivityPercentage': json['totalActivityPercentage'],
        'readRateBytesPerSecond': json['readRateBytesPerSecond'],
        'writeRateBytesPerSecond': json['writeRateBytesPerSecond'],
        'dataReadBytes': json['dataReadBytes'],
        'dataWrittenBytes': json['dataWrittenBytes'],
        'temperatures': json['temperatures'],
    };
}

export function DiskUsageMetricModelToJSON(value?: DiskUsageMetricModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'uniqueIdentifier': value.uniqueIdentifier,
        'serial': value.serial,
        'name': value.name,
        'driveLetter': value.driveLetter,
        'driveType': DriveTypeToJSON(value.driveType),
        'usedSpacePercentage': value.usedSpacePercentage,
        'usedSpaceBytes': value.usedSpaceBytes,
        'writeActivityPercentage': value.writeActivityPercentage,
        'totalActivityPercentage': value.totalActivityPercentage,
        'readRateBytesPerSecond': value.readRateBytesPerSecond,
        'writeRateBytesPerSecond': value.writeRateBytesPerSecond,
        'dataReadBytes': value.dataReadBytes,
        'dataWrittenBytes': value.dataWrittenBytes,
        'temperatures': value.temperatures,
    };
}

