/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DiskUsage } from './DiskUsage';
import {
    DiskUsageFromJSON,
    DiskUsageFromJSONTyped,
    DiskUsageToJSON,
} from './DiskUsage';

/**
 * 
 * @export
 * @interface DiskUsages
 */
export interface DiskUsages {
    /**
     * 
     * @type {{ [key: string]: DiskUsage; }}
     * @memberof DiskUsages
     */
    disks: { [key: string]: DiskUsage; };
}

/**
 * Check if a given object implements the DiskUsages interface.
 */
export function instanceOfDiskUsages(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "disks" in value;

    return isInstance;
}

export function DiskUsagesFromJSON(json: any): DiskUsages {
    return DiskUsagesFromJSONTyped(json, false);
}

export function DiskUsagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiskUsages {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'disks': (mapValues(json['disks'], DiskUsageFromJSON)),
    };
}

export function DiskUsagesToJSON(value?: DiskUsages | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'disks': (mapValues(value.disks, DiskUsageToJSON)),
    };
}

