/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DiskHealth } from './DiskHealth';
import {
    DiskHealthFromJSON,
    DiskHealthFromJSONTyped,
    DiskHealthToJSON,
} from './DiskHealth';
import type { DiskLoad } from './DiskLoad';
import {
    DiskLoadFromJSON,
    DiskLoadFromJSONTyped,
    DiskLoadToJSON,
} from './DiskLoad';
import type { DiskThroughput } from './DiskThroughput';
import {
    DiskThroughputFromJSON,
    DiskThroughputFromJSONTyped,
    DiskThroughputToJSON,
} from './DiskThroughput';
import type { DiskType } from './DiskType';
import {
    DiskTypeFromJSON,
    DiskTypeFromJSONTyped,
    DiskTypeToJSON,
} from './DiskType';

/**
 * 
 * @export
 * @interface Disk
 */
export interface Disk {
    /**
     * 
     * @type {string}
     * @memberof Disk
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Disk
     */
    serial?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Disk
     */
    letter?: string | null;
    /**
     * 
     * @type {DiskType}
     * @memberof Disk
     */
    diskType?: DiskType;
    /**
     * 
     * @type {DiskThroughput}
     * @memberof Disk
     */
    throughput?: DiskThroughput;
    /**
     * 
     * @type {DiskLoad}
     * @memberof Disk
     */
    load?: DiskLoad;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof Disk
     */
    temperatures?: { [key: string]: number; } | null;
    /**
     * 
     * @type {DiskHealth}
     * @memberof Disk
     */
    health?: DiskHealth;
}

/**
 * Check if a given object implements the Disk interface.
 */
export function instanceOfDisk(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DiskFromJSON(json: any): Disk {
    return DiskFromJSONTyped(json, false);
}

export function DiskFromJSONTyped(json: any, ignoreDiscriminator: boolean): Disk {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'serial': !exists(json, 'serial') ? undefined : json['serial'],
        'letter': !exists(json, 'letter') ? undefined : json['letter'],
        'diskType': !exists(json, 'diskType') ? undefined : DiskTypeFromJSON(json['diskType']),
        'throughput': !exists(json, 'throughput') ? undefined : DiskThroughputFromJSON(json['throughput']),
        'load': !exists(json, 'load') ? undefined : DiskLoadFromJSON(json['load']),
        'temperatures': !exists(json, 'temperatures') ? undefined : json['temperatures'],
        'health': !exists(json, 'health') ? undefined : DiskHealthFromJSON(json['health']),
    };
}

export function DiskToJSON(value?: Disk | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'serial': value.serial,
        'letter': value.letter,
        'diskType': DiskTypeToJSON(value.diskType),
        'throughput': DiskThroughputToJSON(value.throughput),
        'load': DiskLoadToJSON(value.load),
        'temperatures': value.temperatures,
        'health': DiskHealthToJSON(value.health),
    };
}

