/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiskLoad
 */
export interface DiskLoad {
    /**
     * 
     * @type {number}
     * @memberof DiskLoad
     */
    usedSpacePercentage: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiskLoad
     */
    usedSpaceBytes: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiskLoad
     */
    totalFreeSpaceBytes: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiskLoad
     */
    writeActivityPercentage: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiskLoad
     */
    totalActivityPercentage: number | null;
}

/**
 * Check if a given object implements the DiskLoad interface.
 */
export function instanceOfDiskLoad(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "usedSpacePercentage" in value;
    isInstance = isInstance && "usedSpaceBytes" in value;
    isInstance = isInstance && "totalFreeSpaceBytes" in value;
    isInstance = isInstance && "writeActivityPercentage" in value;
    isInstance = isInstance && "totalActivityPercentage" in value;

    return isInstance;
}

export function DiskLoadFromJSON(json: any): DiskLoad {
    return DiskLoadFromJSONTyped(json, false);
}

export function DiskLoadFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiskLoad {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'usedSpacePercentage': json['usedSpacePercentage'],
        'usedSpaceBytes': json['usedSpaceBytes'],
        'totalFreeSpaceBytes': json['totalFreeSpaceBytes'],
        'writeActivityPercentage': json['writeActivityPercentage'],
        'totalActivityPercentage': json['totalActivityPercentage'],
    };
}

export function DiskLoadToJSON(value?: DiskLoad | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'usedSpacePercentage': value.usedSpacePercentage,
        'usedSpaceBytes': value.usedSpaceBytes,
        'totalFreeSpaceBytes': value.totalFreeSpaceBytes,
        'writeActivityPercentage': value.writeActivityPercentage,
        'totalActivityPercentage': value.totalActivityPercentage,
    };
}

