/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CpuUsages } from './CpuUsages';
import {
    CpuUsagesFromJSON,
    CpuUsagesFromJSONTyped,
    CpuUsagesToJSON,
} from './CpuUsages';
import type { DiskUsages } from './DiskUsages';
import {
    DiskUsagesFromJSON,
    DiskUsagesFromJSONTyped,
    DiskUsagesToJSON,
} from './DiskUsages';
import type { GpuUsages } from './GpuUsages';
import {
    GpuUsagesFromJSON,
    GpuUsagesFromJSONTyped,
    GpuUsagesToJSON,
} from './GpuUsages';
import type { NetworkAdapters } from './NetworkAdapters';
import {
    NetworkAdaptersFromJSON,
    NetworkAdaptersFromJSONTyped,
    NetworkAdaptersToJSON,
} from './NetworkAdapters';
import type { RamUsages } from './RamUsages';
import {
    RamUsagesFromJSON,
    RamUsagesFromJSONTyped,
    RamUsagesToJSON,
} from './RamUsages';

/**
 * 
 * @export
 * @interface GetMachineDynamicDataResponse
 */
export interface GetMachineDynamicDataResponse {
    /**
     * 
     * @type {CpuUsages}
     * @memberof GetMachineDynamicDataResponse
     */
    cpuUsageData?: CpuUsages;
    /**
     * 
     * @type {RamUsages}
     * @memberof GetMachineDynamicDataResponse
     */
    ramUsagesData?: RamUsages;
    /**
     * 
     * @type {Array<GpuUsages>}
     * @memberof GetMachineDynamicDataResponse
     */
    gpuUsageData?: Array<GpuUsages> | null;
    /**
     * 
     * @type {DiskUsages}
     * @memberof GetMachineDynamicDataResponse
     */
    diskUsages?: DiskUsages;
    /**
     * 
     * @type {NetworkAdapters}
     * @memberof GetMachineDynamicDataResponse
     */
    networkUsageData?: NetworkAdapters;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof GetMachineDynamicDataResponse
     */
    processCpuUsage?: { [key: string]: number; } | null;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof GetMachineDynamicDataResponse
     */
    processCpuThreadsUsage?: { [key: string]: number; } | null;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof GetMachineDynamicDataResponse
     */
    processThreadCount?: { [key: string]: number; } | null;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof GetMachineDynamicDataResponse
     */
    processRamUsageGb?: { [key: string]: number; } | null;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof GetMachineDynamicDataResponse
     */
    processDiskBytesPerSecActivity?: { [key: string]: number; } | null;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof GetMachineDynamicDataResponse
     */
    cpuTemperature?: { [key: string]: number; } | null;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof GetMachineDynamicDataResponse
     */
    processGpuUsage?: { [key: string]: number; } | null;
}

/**
 * Check if a given object implements the GetMachineDynamicDataResponse interface.
 */
export function instanceOfGetMachineDynamicDataResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetMachineDynamicDataResponseFromJSON(json: any): GetMachineDynamicDataResponse {
    return GetMachineDynamicDataResponseFromJSONTyped(json, false);
}

export function GetMachineDynamicDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMachineDynamicDataResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cpuUsageData': !exists(json, 'cpuUsageData') ? undefined : CpuUsagesFromJSON(json['cpuUsageData']),
        'ramUsagesData': !exists(json, 'ramUsagesData') ? undefined : RamUsagesFromJSON(json['ramUsagesData']),
        'gpuUsageData': !exists(json, 'gpuUsageData') ? undefined : (json['gpuUsageData'] === null ? null : (json['gpuUsageData'] as Array<any>).map(GpuUsagesFromJSON)),
        'diskUsages': !exists(json, 'diskUsages') ? undefined : DiskUsagesFromJSON(json['diskUsages']),
        'networkUsageData': !exists(json, 'networkUsageData') ? undefined : NetworkAdaptersFromJSON(json['networkUsageData']),
        'processCpuUsage': !exists(json, 'processCpuUsage') ? undefined : json['processCpuUsage'],
        'processCpuThreadsUsage': !exists(json, 'processCpuThreadsUsage') ? undefined : json['processCpuThreadsUsage'],
        'processThreadCount': !exists(json, 'processThreadCount') ? undefined : json['processThreadCount'],
        'processRamUsageGb': !exists(json, 'processRamUsageGb') ? undefined : json['processRamUsageGb'],
        'processDiskBytesPerSecActivity': !exists(json, 'processDiskBytesPerSecActivity') ? undefined : json['processDiskBytesPerSecActivity'],
        'cpuTemperature': !exists(json, 'cpuTemperature') ? undefined : json['cpuTemperature'],
        'processGpuUsage': !exists(json, 'processGpuUsage') ? undefined : json['processGpuUsage'],
    };
}

export function GetMachineDynamicDataResponseToJSON(value?: GetMachineDynamicDataResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cpuUsageData': CpuUsagesToJSON(value.cpuUsageData),
        'ramUsagesData': RamUsagesToJSON(value.ramUsagesData),
        'gpuUsageData': value.gpuUsageData === undefined ? undefined : (value.gpuUsageData === null ? null : (value.gpuUsageData as Array<any>).map(GpuUsagesToJSON)),
        'diskUsages': DiskUsagesToJSON(value.diskUsages),
        'networkUsageData': NetworkAdaptersToJSON(value.networkUsageData),
        'processCpuUsage': value.processCpuUsage,
        'processCpuThreadsUsage': value.processCpuThreadsUsage,
        'processThreadCount': value.processThreadCount,
        'processRamUsageGb': value.processRamUsageGb,
        'processDiskBytesPerSecActivity': value.processDiskBytesPerSecActivity,
        'cpuTemperature': value.cpuTemperature,
        'processGpuUsage': value.processGpuUsage,
    };
}

