/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProcessToAddDto } from './ProcessToAddDto';
import {
    ProcessToAddDtoFromJSON,
    ProcessToAddDtoFromJSONTyped,
    ProcessToAddDtoToJSON,
} from './ProcessToAddDto';

/**
 * 
 * @export
 * @interface GetProcessesToAddResponse
 */
export interface GetProcessesToAddResponse {
    /**
     * 
     * @type {Array<ProcessToAddDto>}
     * @memberof GetProcessesToAddResponse
     */
    processes: Array<ProcessToAddDto>;
}

/**
 * Check if a given object implements the GetProcessesToAddResponse interface.
 */
export function instanceOfGetProcessesToAddResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "processes" in value;

    return isInstance;
}

export function GetProcessesToAddResponseFromJSON(json: any): GetProcessesToAddResponse {
    return GetProcessesToAddResponseFromJSONTyped(json, false);
}

export function GetProcessesToAddResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProcessesToAddResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'processes': ((json['processes'] as Array<any>).map(ProcessToAddDtoFromJSON)),
    };
}

export function GetProcessesToAddResponseToJSON(value?: GetProcessesToAddResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'processes': ((value.processes as Array<any>).map(ProcessToAddDtoToJSON)),
    };
}

