/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ParentChildModelDto } from './ParentChildModelDto';
import {
    ParentChildModelDtoFromJSON,
    ParentChildModelDtoFromJSONTyped,
    ParentChildModelDtoToJSON,
} from './ParentChildModelDto';

/**
 * 
 * @export
 * @interface GetRunningProcessesResponse
 */
export interface GetRunningProcessesResponse {
    /**
     * 
     * @type {{ [key: string]: ParentChildModelDto; }}
     * @memberof GetRunningProcessesResponse
     */
    processView?: { [key: string]: ParentChildModelDto; } | null;
}

/**
 * Check if a given object implements the GetRunningProcessesResponse interface.
 */
export function instanceOfGetRunningProcessesResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetRunningProcessesResponseFromJSON(json: any): GetRunningProcessesResponse {
    return GetRunningProcessesResponseFromJSONTyped(json, false);
}

export function GetRunningProcessesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRunningProcessesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'processView': !exists(json, 'processView') ? undefined : (json['processView'] === null ? null : mapValues(json['processView'], ParentChildModelDtoFromJSON)),
    };
}

export function GetRunningProcessesResponseToJSON(value?: GetRunningProcessesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'processView': value.processView === undefined ? undefined : (value.processView === null ? null : mapValues(value.processView, ParentChildModelDtoToJSON)),
    };
}

