/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LoadData } from './LoadData';
import {
    LoadDataFromJSON,
    LoadDataFromJSONTyped,
    LoadDataToJSON,
} from './LoadData';
import type { PCIEThroughPut } from './PCIEThroughPut';
import {
    PCIEThroughPutFromJSON,
    PCIEThroughPutFromJSONTyped,
    PCIEThroughPutToJSON,
} from './PCIEThroughPut';

/**
 * 
 * @export
 * @interface GpuUsages
 */
export interface GpuUsages {
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof GpuUsages
     */
    temperatureReadings: { [key: string]: number; };
    /**
     * 
     * @type {number}
     * @memberof GpuUsages
     */
    totalMemoryBytes: number | null;
    /**
     * 
     * @type {number}
     * @memberof GpuUsages
     */
    memoryUsedBytes: number | null;
    /**
     * 
     * @type {number}
     * @memberof GpuUsages
     */
    memoryClockMhz: number | null;
    /**
     * 
     * @type {number}
     * @memberof GpuUsages
     */
    shaderClockMhz: number | null;
    /**
     * 
     * @type {number}
     * @memberof GpuUsages
     */
    coreClockMhz: number | null;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof GpuUsages
     */
    fanPercentage: { [key: string]: number; } | null;
    /**
     * 
     * @type {number}
     * @memberof GpuUsages
     */
    powerDraw: number | null;
    /**
     * 
     * @type {LoadData}
     * @memberof GpuUsages
     */
    load: LoadData;
    /**
     * 
     * @type {PCIEThroughPut}
     * @memberof GpuUsages
     */
    pcIeThroughput?: PCIEThroughPut;
}

/**
 * Check if a given object implements the GpuUsages interface.
 */
export function instanceOfGpuUsages(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "temperatureReadings" in value;
    isInstance = isInstance && "totalMemoryBytes" in value;
    isInstance = isInstance && "memoryUsedBytes" in value;
    isInstance = isInstance && "memoryClockMhz" in value;
    isInstance = isInstance && "shaderClockMhz" in value;
    isInstance = isInstance && "coreClockMhz" in value;
    isInstance = isInstance && "fanPercentage" in value;
    isInstance = isInstance && "powerDraw" in value;
    isInstance = isInstance && "load" in value;

    return isInstance;
}

export function GpuUsagesFromJSON(json: any): GpuUsages {
    return GpuUsagesFromJSONTyped(json, false);
}

export function GpuUsagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GpuUsages {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'temperatureReadings': json['temperatureReadings'],
        'totalMemoryBytes': json['totalMemoryBytes'],
        'memoryUsedBytes': json['memoryUsedBytes'],
        'memoryClockMhz': json['memoryClockMhz'],
        'shaderClockMhz': json['shaderClockMhz'],
        'coreClockMhz': json['coreClockMhz'],
        'fanPercentage': json['fanPercentage'],
        'powerDraw': json['powerDraw'],
        'load': LoadDataFromJSON(json['load']),
        'pcIeThroughput': !exists(json, 'pcIe_Throughput') ? undefined : PCIEThroughPutFromJSON(json['pcIe_Throughput']),
    };
}

export function GpuUsagesToJSON(value?: GpuUsages | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'temperatureReadings': value.temperatureReadings,
        'totalMemoryBytes': value.totalMemoryBytes,
        'memoryUsedBytes': value.memoryUsedBytes,
        'memoryClockMhz': value.memoryClockMhz,
        'shaderClockMhz': value.shaderClockMhz,
        'coreClockMhz': value.coreClockMhz,
        'fanPercentage': value.fanPercentage,
        'powerDraw': value.powerDraw,
        'load': LoadDataToJSON(value.load),
        'pcIe_Throughput': PCIEThroughPutToJSON(value.pcIeThroughput),
    };
}

