/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HardwareMetricModel
 */
export interface HardwareMetricModel {
    /**
     * 
     * @type {number}
     * @memberof HardwareMetricModel
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof HardwareMetricModel
     */
    uniqueIdentifier?: string;
}

/**
 * Check if a given object implements the HardwareMetricModel interface.
 */
export function instanceOfHardwareMetricModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function HardwareMetricModelFromJSON(json: any): HardwareMetricModel {
    return HardwareMetricModelFromJSONTyped(json, false);
}

export function HardwareMetricModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): HardwareMetricModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'uniqueIdentifier': !exists(json, 'uniqueIdentifier') ? undefined : json['uniqueIdentifier'],
    };
}

export function HardwareMetricModelToJSON(value?: HardwareMetricModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'uniqueIdentifier': value.uniqueIdentifier,
    };
}

