/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IPInterfaceProperties
 */
export interface IPInterfaceProperties {
    /**
     * 
     * @type {string}
     * @memberof IPInterfaceProperties
     */
    iPv4Address: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPInterfaceProperties
     */
    iPv6Address: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPInterfaceProperties
     */
    dnsSuffix: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof IPInterfaceProperties
     */
    isDnsEnabled: boolean;
}

/**
 * Check if a given object implements the IPInterfaceProperties interface.
 */
export function instanceOfIPInterfaceProperties(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "iPv4Address" in value;
    isInstance = isInstance && "iPv6Address" in value;
    isInstance = isInstance && "dnsSuffix" in value;
    isInstance = isInstance && "isDnsEnabled" in value;

    return isInstance;
}

export function IPInterfacePropertiesFromJSON(json: any): IPInterfaceProperties {
    return IPInterfacePropertiesFromJSONTyped(json, false);
}

export function IPInterfacePropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): IPInterfaceProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'iPv4Address': json['iPv4Address'],
        'iPv6Address': json['iPv6Address'],
        'dnsSuffix': json['dnsSuffix'],
        'isDnsEnabled': json['isDnsEnabled'],
    };
}

export function IPInterfacePropertiesToJSON(value?: IPInterfaceProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'iPv4Address': value.iPv4Address,
        'iPv6Address': value.iPv6Address,
        'dnsSuffix': value.dnsSuffix,
        'isDnsEnabled': value.isDnsEnabled,
    };
}

