/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LaunchSettings
 */
export interface LaunchSettings {
    /**
     * 
     * @type {number}
     * @memberof LaunchSettings
     */
    vitalServiceHttpsPort: number;
    /**
     * 
     * @type {number}
     * @memberof LaunchSettings
     */
    vitalServiceHttpPort: number;
}

/**
 * Check if a given object implements the LaunchSettings interface.
 */
export function instanceOfLaunchSettings(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "vitalServiceHttpsPort" in value;
    isInstance = isInstance && "vitalServiceHttpPort" in value;

    return isInstance;
}

export function LaunchSettingsFromJSON(json: any): LaunchSettings {
    return LaunchSettingsFromJSONTyped(json, false);
}

export function LaunchSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaunchSettings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'vitalServiceHttpsPort': json['vitalServiceHttpsPort'],
        'vitalServiceHttpPort': json['vitalServiceHttpPort'],
    };
}

export function LaunchSettingsToJSON(value?: LaunchSettings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'vitalServiceHttpsPort': value.vitalServiceHttpsPort,
        'vitalServiceHttpPort': value.vitalServiceHttpPort,
    };
}

