/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoadData
 */
export interface LoadData {
    /**
     * 
     * @type {number}
     * @memberof LoadData
     */
    corePercentage?: number;
    /**
     * 
     * @type {number}
     * @memberof LoadData
     */
    frameBufferPercentage?: number;
    /**
     * 
     * @type {number}
     * @memberof LoadData
     */
    videoEnginePercentage?: number;
    /**
     * 
     * @type {number}
     * @memberof LoadData
     */
    busInterfacePercentage?: number;
    /**
     * 
     * @type {number}
     * @memberof LoadData
     */
    memoryUsedPercentage?: number;
    /**
     * 
     * @type {number}
     * @memberof LoadData
     */
    memoryControllerPercentage?: number;
    /**
     * 
     * @type {number}
     * @memberof LoadData
     */
    cudaPercentage?: number;
    /**
     * 
     * @type {number}
     * @memberof LoadData
     */
    threeDPercentage?: number;
}

/**
 * Check if a given object implements the LoadData interface.
 */
export function instanceOfLoadData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LoadDataFromJSON(json: any): LoadData {
    return LoadDataFromJSONTyped(json, false);
}

export function LoadDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoadData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'corePercentage': !exists(json, 'corePercentage') ? undefined : json['corePercentage'],
        'frameBufferPercentage': !exists(json, 'frameBufferPercentage') ? undefined : json['frameBufferPercentage'],
        'videoEnginePercentage': !exists(json, 'videoEnginePercentage') ? undefined : json['videoEnginePercentage'],
        'busInterfacePercentage': !exists(json, 'busInterfacePercentage') ? undefined : json['busInterfacePercentage'],
        'memoryUsedPercentage': !exists(json, 'memoryUsedPercentage') ? undefined : json['memoryUsedPercentage'],
        'memoryControllerPercentage': !exists(json, 'memoryControllerPercentage') ? undefined : json['memoryControllerPercentage'],
        'cudaPercentage': !exists(json, 'cudaPercentage') ? undefined : json['cudaPercentage'],
        'threeDPercentage': !exists(json, 'threeDPercentage') ? undefined : json['threeDPercentage'],
    };
}

export function LoadDataToJSON(value?: LoadData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'corePercentage': value.corePercentage,
        'frameBufferPercentage': value.frameBufferPercentage,
        'videoEnginePercentage': value.videoEnginePercentage,
        'busInterfacePercentage': value.busInterfacePercentage,
        'memoryUsedPercentage': value.memoryUsedPercentage,
        'memoryControllerPercentage': value.memoryControllerPercentage,
        'cudaPercentage': value.cudaPercentage,
        'threeDPercentage': value.threeDPercentage,
    };
}

