/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoadData
 */
export interface LoadData {
    /**
     * 
     * @type {number}
     * @memberof LoadData
     */
    core?: number;
    /**
     * 
     * @type {number}
     * @memberof LoadData
     */
    frameBuffer?: number;
    /**
     * 
     * @type {number}
     * @memberof LoadData
     */
    videoEngine?: number;
    /**
     * 
     * @type {number}
     * @memberof LoadData
     */
    busInterface?: number;
    /**
     * 
     * @type {number}
     * @memberof LoadData
     */
    memory?: number;
    /**
     * 
     * @type {number}
     * @memberof LoadData
     */
    memoryController?: number;
    /**
     * 
     * @type {number}
     * @memberof LoadData
     */
    cuda?: number;
    /**
     * 
     * @type {number}
     * @memberof LoadData
     */
    threeD?: number;
}

/**
 * Check if a given object implements the LoadData interface.
 */
export function instanceOfLoadData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LoadDataFromJSON(json: any): LoadData {
    return LoadDataFromJSONTyped(json, false);
}

export function LoadDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoadData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'core': !exists(json, 'core') ? undefined : json['core'],
        'frameBuffer': !exists(json, 'frameBuffer') ? undefined : json['frameBuffer'],
        'videoEngine': !exists(json, 'videoEngine') ? undefined : json['videoEngine'],
        'busInterface': !exists(json, 'busInterface') ? undefined : json['busInterface'],
        'memory': !exists(json, 'memory') ? undefined : json['memory'],
        'memoryController': !exists(json, 'memoryController') ? undefined : json['memoryController'],
        'cuda': !exists(json, 'cuda') ? undefined : json['cuda'],
        'threeD': !exists(json, 'threeD') ? undefined : json['threeD'],
    };
}

export function LoadDataToJSON(value?: LoadData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'core': value.core,
        'frameBuffer': value.frameBuffer,
        'videoEngine': value.videoEngine,
        'busInterface': value.busInterface,
        'memory': value.memory,
        'memoryController': value.memoryController,
        'cuda': value.cuda,
        'threeD': value.threeD,
    };
}

