/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemUsage
 */
export interface MemUsage {
    /**
     * 
     * @type {number}
     * @memberof MemUsage
     */
    memPercentage?: number;
    /**
     * 
     * @type {number}
     * @memberof MemUsage
     */
    memUsedKB?: number;
    /**
     * 
     * @type {number}
     * @memberof MemUsage
     */
    memTotalKB?: number;
    /**
     * 
     * @type {number}
     * @memberof MemUsage
     */
    swapPercentage?: number;
    /**
     * 
     * @type {number}
     * @memberof MemUsage
     */
    swapUsedKB?: number;
    /**
     * 
     * @type {number}
     * @memberof MemUsage
     */
    swapTotalKB?: number;
}

/**
 * Check if a given object implements the MemUsage interface.
 */
export function instanceOfMemUsage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MemUsageFromJSON(json: any): MemUsage {
    return MemUsageFromJSONTyped(json, false);
}

export function MemUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemUsage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'memPercentage': !exists(json, 'memPercentage') ? undefined : json['memPercentage'],
        'memUsedKB': !exists(json, 'memUsedKB') ? undefined : json['memUsedKB'],
        'memTotalKB': !exists(json, 'memTotalKB') ? undefined : json['memTotalKB'],
        'swapPercentage': !exists(json, 'swapPercentage') ? undefined : json['swapPercentage'],
        'swapUsedKB': !exists(json, 'swapUsedKB') ? undefined : json['swapUsedKB'],
        'swapTotalKB': !exists(json, 'swapTotalKB') ? undefined : json['swapTotalKB'],
    };
}

export function MemUsageToJSON(value?: MemUsage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'memPercentage': value.memPercentage,
        'memUsedKB': value.memUsedKB,
        'memTotalKB': value.memTotalKB,
        'swapPercentage': value.swapPercentage,
        'swapUsedKB': value.swapUsedKB,
        'swapTotalKB': value.swapTotalKB,
    };
}

