/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NetworkUsageMetricModel
 */
export interface NetworkUsageMetricModel {
    /**
     * 
     * @type {number}
     * @memberof NetworkUsageMetricModel
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof NetworkUsageMetricModel
     */
    uniqueIdentifier?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NetworkUsageMetricModel
     */
    uploadSpeedBps?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NetworkUsageMetricModel
     */
    downloadSpeedBps?: number | null;
}

/**
 * Check if a given object implements the NetworkUsageMetricModel interface.
 */
export function instanceOfNetworkUsageMetricModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NetworkUsageMetricModelFromJSON(json: any): NetworkUsageMetricModel {
    return NetworkUsageMetricModelFromJSONTyped(json, false);
}

export function NetworkUsageMetricModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkUsageMetricModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'uniqueIdentifier': !exists(json, 'uniqueIdentifier') ? undefined : json['uniqueIdentifier'],
        'uploadSpeedBps': !exists(json, 'uploadSpeedBps') ? undefined : json['uploadSpeedBps'],
        'downloadSpeedBps': !exists(json, 'downloadSpeedBps') ? undefined : json['downloadSpeedBps'],
    };
}

export function NetworkUsageMetricModelToJSON(value?: NetworkUsageMetricModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'uniqueIdentifier': value.uniqueIdentifier,
        'uploadSpeedBps': value.uploadSpeedBps,
        'downloadSpeedBps': value.downloadSpeedBps,
    };
}

