/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IPInterfaceProperties } from './IPInterfaceProperties';
import {
    IPInterfacePropertiesFromJSON,
    IPInterfacePropertiesFromJSONTyped,
    IPInterfacePropertiesToJSON,
} from './IPInterfaceProperties';

/**
 * 
 * @export
 * @interface NetworkAdapterProperties
 */
export interface NetworkAdapterProperties {
    /**
     * 
     * @type {IPInterfaceProperties}
     * @memberof NetworkAdapterProperties
     */
    ipInterfaceProperties?: IPInterfaceProperties;
    /**
     * 
     * @type {string}
     * @memberof NetworkAdapterProperties
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkAdapterProperties
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkAdapterProperties
     */
    macAddress: string;
    /**
     * 
     * @type {number}
     * @memberof NetworkAdapterProperties
     */
    speedBps?: number;
    /**
     * 
     * @type {string}
     * @memberof NetworkAdapterProperties
     */
    connectionType?: string;
}

/**
 * Check if a given object implements the NetworkAdapterProperties interface.
 */
export function instanceOfNetworkAdapterProperties(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "macAddress" in value;

    return isInstance;
}

export function NetworkAdapterPropertiesFromJSON(json: any): NetworkAdapterProperties {
    return NetworkAdapterPropertiesFromJSONTyped(json, false);
}

export function NetworkAdapterPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkAdapterProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ipInterfaceProperties': !exists(json, 'ipInterfaceProperties') ? undefined : IPInterfacePropertiesFromJSON(json['ipInterfaceProperties']),
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'macAddress': json['macAddress'],
        'speedBps': !exists(json, 'speedBps') ? undefined : json['speedBps'],
        'connectionType': !exists(json, 'connectionType') ? undefined : json['connectionType'],
    };
}

export function NetworkAdapterPropertiesToJSON(value?: NetworkAdapterProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ipInterfaceProperties': IPInterfacePropertiesToJSON(value.ipInterfaceProperties),
        'name': value.name,
        'description': value.description,
        'macAddress': value.macAddress,
        'speedBps': value.speedBps,
        'connectionType': value.connectionType,
    };
}

