/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcessGpuUtil
 */
export interface ProcessGpuUtil {
    /**
     * 
     * @type {number}
     * @memberof ProcessGpuUtil
     */
    gpuCorePercentage: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProcessGpuUtil
     */
    gpuMemPercentage: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProcessGpuUtil
     */
    gpuEncodingPercentage: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProcessGpuUtil
     */
    gpuDecodingPercentage: number | null;
}

/**
 * Check if a given object implements the ProcessGpuUtil interface.
 */
export function instanceOfProcessGpuUtil(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "gpuCorePercentage" in value;
    isInstance = isInstance && "gpuMemPercentage" in value;
    isInstance = isInstance && "gpuEncodingPercentage" in value;
    isInstance = isInstance && "gpuDecodingPercentage" in value;

    return isInstance;
}

export function ProcessGpuUtilFromJSON(json: any): ProcessGpuUtil {
    return ProcessGpuUtilFromJSONTyped(json, false);
}

export function ProcessGpuUtilFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessGpuUtil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gpuCorePercentage': json['gpuCorePercentage'],
        'gpuMemPercentage': json['gpuMemPercentage'],
        'gpuEncodingPercentage': json['gpuEncodingPercentage'],
        'gpuDecodingPercentage': json['gpuDecodingPercentage'],
    };
}

export function ProcessGpuUtilToJSON(value?: ProcessGpuUtil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gpuCorePercentage': value.gpuCorePercentage,
        'gpuMemPercentage': value.gpuMemPercentage,
        'gpuEncodingPercentage': value.gpuEncodingPercentage,
        'gpuDecodingPercentage': value.gpuDecodingPercentage,
    };
}

