/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProcessDiskUsage } from './ProcessDiskUsage';
import {
    ProcessDiskUsageFromJSON,
    ProcessDiskUsageFromJSONTyped,
    ProcessDiskUsageToJSON,
} from './ProcessDiskUsage';
import type { ProcessGpuUtil } from './ProcessGpuUtil';
import {
    ProcessGpuUtilFromJSON,
    ProcessGpuUtilFromJSONTyped,
    ProcessGpuUtilToJSON,
} from './ProcessGpuUtil';

/**
 * 
 * @export
 * @interface ProcessData
 */
export interface ProcessData {
    /**
     * 
     * @type {number}
     * @memberof ProcessData
     */
    pid: number;
    /**
     * 
     * @type {number}
     * @memberof ProcessData
     */
    parentPid: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProcessData
     */
    executablePath: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProcessData
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProcessData
     */
    mainWindowTitle: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProcessData
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof ProcessData
     */
    timeStamp: Date;
    /**
     * 
     * @type {number}
     * @memberof ProcessData
     */
    cpuPercentage: number;
    /**
     * 
     * @type {number}
     * @memberof ProcessData
     */
    memoryKb: number;
    /**
     * 
     * @type {ProcessDiskUsage}
     * @memberof ProcessData
     */
    diskUsage: ProcessDiskUsage;
    /**
     * 
     * @type {string}
     * @memberof ProcessData
     */
    status: string | null;
    /**
     * 
     * @type {ProcessGpuUtil}
     * @memberof ProcessData
     */
    gpuUtil: ProcessGpuUtil;
}

/**
 * Check if a given object implements the ProcessData interface.
 */
export function instanceOfProcessData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pid" in value;
    isInstance = isInstance && "parentPid" in value;
    isInstance = isInstance && "executablePath" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "mainWindowTitle" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "timeStamp" in value;
    isInstance = isInstance && "cpuPercentage" in value;
    isInstance = isInstance && "memoryKb" in value;
    isInstance = isInstance && "diskUsage" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "gpuUtil" in value;

    return isInstance;
}

export function ProcessDataFromJSON(json: any): ProcessData {
    return ProcessDataFromJSONTyped(json, false);
}

export function ProcessDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pid': json['pid'],
        'parentPid': json['parentPid'],
        'executablePath': json['executablePath'],
        'description': json['description'],
        'mainWindowTitle': json['mainWindowTitle'],
        'name': json['name'],
        'timeStamp': (new Date(json['timeStamp'])),
        'cpuPercentage': json['cpuPercentage'],
        'memoryKb': json['memoryKb'],
        'diskUsage': ProcessDiskUsageFromJSON(json['diskUsage']),
        'status': json['status'],
        'gpuUtil': ProcessGpuUtilFromJSON(json['gpuUtil']),
    };
}

export function ProcessDataToJSON(value?: ProcessData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pid': value.pid,
        'parentPid': value.parentPid,
        'executablePath': value.executablePath,
        'description': value.description,
        'mainWindowTitle': value.mainWindowTitle,
        'name': value.name,
        'timeStamp': (value.timeStamp.toISOString()),
        'cpuPercentage': value.cpuPercentage,
        'memoryKb': value.memoryKb,
        'diskUsage': ProcessDiskUsageToJSON(value.diskUsage),
        'status': value.status,
        'gpuUtil': ProcessGpuUtilToJSON(value.gpuUtil),
    };
}

