/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProcessDiskUsage } from './ProcessDiskUsage';
import {
    ProcessDiskUsageFromJSON,
    ProcessDiskUsageFromJSONTyped,
    ProcessDiskUsageToJSON,
} from './ProcessDiskUsage';
import type { ProcessGpuUtil } from './ProcessGpuUtil';
import {
    ProcessGpuUtilFromJSON,
    ProcessGpuUtilFromJSONTyped,
    ProcessGpuUtilToJSON,
} from './ProcessGpuUtil';

/**
 * 
 * @export
 * @interface ProcessData
 */
export interface ProcessData {
    /**
     * 
     * @type {number}
     * @memberof ProcessData
     */
    pid?: number;
    /**
     * 
     * @type {number}
     * @memberof ProcessData
     */
    parentPid?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProcessData
     */
    executablePath?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProcessData
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProcessData
     */
    mainWindowTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProcessData
     */
    name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ProcessData
     */
    timeStamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof ProcessData
     */
    cpuPercentage?: number;
    /**
     * 
     * @type {number}
     * @memberof ProcessData
     */
    memoryKb?: number;
    /**
     * 
     * @type {ProcessDiskUsage}
     * @memberof ProcessData
     */
    diskUsage?: ProcessDiskUsage;
    /**
     * 
     * @type {string}
     * @memberof ProcessData
     */
    status?: string | null;
    /**
     * 
     * @type {ProcessGpuUtil}
     * @memberof ProcessData
     */
    gpuUtil?: ProcessGpuUtil;
}

/**
 * Check if a given object implements the ProcessData interface.
 */
export function instanceOfProcessData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProcessDataFromJSON(json: any): ProcessData {
    return ProcessDataFromJSONTyped(json, false);
}

export function ProcessDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pid': !exists(json, 'pid') ? undefined : json['pid'],
        'parentPid': !exists(json, 'parentPid') ? undefined : json['parentPid'],
        'executablePath': !exists(json, 'executablePath') ? undefined : json['executablePath'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'mainWindowTitle': !exists(json, 'mainWindowTitle') ? undefined : json['mainWindowTitle'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'timeStamp': !exists(json, 'timeStamp') ? undefined : (new Date(json['timeStamp'])),
        'cpuPercentage': !exists(json, 'cpuPercentage') ? undefined : json['cpuPercentage'],
        'memoryKb': !exists(json, 'memoryKb') ? undefined : json['memoryKb'],
        'diskUsage': !exists(json, 'diskUsage') ? undefined : ProcessDiskUsageFromJSON(json['diskUsage']),
        'status': !exists(json, 'status') ? undefined : json['status'],
        'gpuUtil': !exists(json, 'gpuUtil') ? undefined : ProcessGpuUtilFromJSON(json['gpuUtil']),
    };
}

export function ProcessDataToJSON(value?: ProcessData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pid': value.pid,
        'parentPid': value.parentPid,
        'executablePath': value.executablePath,
        'description': value.description,
        'mainWindowTitle': value.mainWindowTitle,
        'name': value.name,
        'timeStamp': value.timeStamp === undefined ? undefined : (value.timeStamp.toISOString()),
        'cpuPercentage': value.cpuPercentage,
        'memoryKb': value.memoryKb,
        'diskUsage': ProcessDiskUsageToJSON(value.diskUsage),
        'status': value.status,
        'gpuUtil': ProcessGpuUtilToJSON(value.gpuUtil),
    };
}

