/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileDto
 */
export interface ProfileDto {
    /**
     * 
     * @type {number}
     * @memberof ProfileDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProfileDto
     */
    name?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof ProfileDto
     */
    managedModelsIds?: Array<number> | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProfileDto
     */
    enabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProfileDto
     */
    active?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProfileDto
     */
    priority?: number | null;
}

/**
 * Check if a given object implements the ProfileDto interface.
 */
export function instanceOfProfileDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfileDtoFromJSON(json: any): ProfileDto {
    return ProfileDtoFromJSONTyped(json, false);
}

export function ProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'managedModelsIds': !exists(json, 'managedModelsIds') ? undefined : json['managedModelsIds'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'active': !exists(json, 'active') ? undefined : json['active'],
        'priority': !exists(json, 'priority') ? undefined : json['priority'],
    };
}

export function ProfileDtoToJSON(value?: ProfileDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'managedModelsIds': value.managedModelsIds,
        'enabled': value.enabled,
        'active': value.active,
        'priority': value.priority,
    };
}

