/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RamData
 */
export interface RamData {
    /**
     * 
     * @type {string}
     * @memberof RamData
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RamData
     */
    partNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof RamData
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof RamData
     */
    speedMhz?: number;
    /**
     * 
     * @type {number}
     * @memberof RamData
     */
    slotNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof RamData
     */
    slotChannel?: string;
    /**
     * 
     * @type {number}
     * @memberof RamData
     */
    configuredClockSpeedMhz?: number;
    /**
     * 
     * @type {number}
     * @memberof RamData
     */
    capacity?: number;
}

/**
 * Check if a given object implements the RamData interface.
 */
export function instanceOfRamData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RamDataFromJSON(json: any): RamData {
    return RamDataFromJSONTyped(json, false);
}

export function RamDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RamData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'partNumber': !exists(json, 'partNumber') ? undefined : json['partNumber'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'speedMhz': !exists(json, 'speedMhz') ? undefined : json['speedMhz'],
        'slotNumber': !exists(json, 'slotNumber') ? undefined : json['slotNumber'],
        'slotChannel': !exists(json, 'slotChannel') ? undefined : json['slotChannel'],
        'configuredClockSpeedMhz': !exists(json, 'configuredClockSpeedMhz') ? undefined : json['configuredClockSpeedMhz'],
        'capacity': !exists(json, 'capacity') ? undefined : json['capacity'],
    };
}

export function RamDataToJSON(value?: RamData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'partNumber': value.partNumber,
        'type': value.type,
        'speedMhz': value.speedMhz,
        'slotNumber': value.slotNumber,
        'slotChannel': value.slotChannel,
        'configuredClockSpeedMhz': value.configuredClockSpeedMhz,
        'capacity': value.capacity,
    };
}

