/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RamUsageMetricModel
 */
export interface RamUsageMetricModel {
    /**
     * 
     * @type {number}
     * @memberof RamUsageMetricModel
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof RamUsageMetricModel
     */
    uniqueIdentifier: string | null;
    /**
     * 
     * @type {number}
     * @memberof RamUsageMetricModel
     */
    usedMemoryBytes: number | null;
    /**
     * 
     * @type {number}
     * @memberof RamUsageMetricModel
     */
    totalVisibleMemoryBytes: number | null;
}

/**
 * Check if a given object implements the RamUsageMetricModel interface.
 */
export function instanceOfRamUsageMetricModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "uniqueIdentifier" in value;
    isInstance = isInstance && "usedMemoryBytes" in value;
    isInstance = isInstance && "totalVisibleMemoryBytes" in value;

    return isInstance;
}

export function RamUsageMetricModelFromJSON(json: any): RamUsageMetricModel {
    return RamUsageMetricModelFromJSONTyped(json, false);
}

export function RamUsageMetricModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RamUsageMetricModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'uniqueIdentifier': json['uniqueIdentifier'],
        'usedMemoryBytes': json['usedMemoryBytes'],
        'totalVisibleMemoryBytes': json['totalVisibleMemoryBytes'],
    };
}

export function RamUsageMetricModelToJSON(value?: RamUsageMetricModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'uniqueIdentifier': value.uniqueIdentifier,
        'usedMemoryBytes': value.usedMemoryBytes,
        'totalVisibleMemoryBytes': value.totalVisibleMemoryBytes,
    };
}

