/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProcessData } from './ProcessData';
import {
    ProcessDataFromJSON,
    ProcessDataFromJSONTyped,
    ProcessDataToJSON,
} from './ProcessData';
import type { SystemUsage } from './SystemUsage';
import {
    SystemUsageFromJSON,
    SystemUsageFromJSONTyped,
    SystemUsageToJSON,
} from './SystemUsage';

/**
 * 
 * @export
 * @interface SendUtilizationRequest
 */
export interface SendUtilizationRequest {
    /**
     * 
     * @type {Array<ProcessData>}
     * @memberof SendUtilizationRequest
     */
    processData?: Array<ProcessData> | null;
    /**
     * 
     * @type {SystemUsage}
     * @memberof SendUtilizationRequest
     */
    systemUsage?: SystemUsage;
}

/**
 * Check if a given object implements the SendUtilizationRequest interface.
 */
export function instanceOfSendUtilizationRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SendUtilizationRequestFromJSON(json: any): SendUtilizationRequest {
    return SendUtilizationRequestFromJSONTyped(json, false);
}

export function SendUtilizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendUtilizationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'processData': !exists(json, 'processData') ? undefined : (json['processData'] === null ? null : (json['processData'] as Array<any>).map(ProcessDataFromJSON)),
        'systemUsage': !exists(json, 'systemUsage') ? undefined : SystemUsageFromJSON(json['systemUsage']),
    };
}

export function SendUtilizationRequestToJSON(value?: SendUtilizationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'processData': value.processData === undefined ? undefined : (value.processData === null ? null : (value.processData as Array<any>).map(ProcessDataToJSON)),
        'systemUsage': SystemUsageToJSON(value.systemUsage),
    };
}

