/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CpuUsage } from './CpuUsage';
import {
    CpuUsageFromJSON,
    CpuUsageFromJSONTyped,
    CpuUsageToJSON,
} from './CpuUsage';
import type { Disk } from './Disk';
import {
    DiskFromJSON,
    DiskFromJSONTyped,
    DiskToJSON,
} from './Disk';
import type { MemUsage } from './MemUsage';
import {
    MemUsageFromJSON,
    MemUsageFromJSONTyped,
    MemUsageToJSON,
} from './MemUsage';
import type { NetworkAdapterUsage } from './NetworkAdapterUsage';
import {
    NetworkAdapterUsageFromJSON,
    NetworkAdapterUsageFromJSONTyped,
    NetworkAdapterUsageToJSON,
} from './NetworkAdapterUsage';

/**
 * 
 * @export
 * @interface SystemUsage
 */
export interface SystemUsage {
    /**
     * 
     * @type {CpuUsage}
     * @memberof SystemUsage
     */
    cpuUsage?: CpuUsage;
    /**
     * 
     * @type {MemUsage}
     * @memberof SystemUsage
     */
    memUsage?: MemUsage;
    /**
     * 
     * @type {Array<NetworkAdapterUsage>}
     * @memberof SystemUsage
     */
    networkAdapterUsage?: Array<NetworkAdapterUsage>;
    /**
     * 
     * @type {{ [key: string]: Disk; }}
     * @memberof SystemUsage
     */
    disk?: { [key: string]: Disk; };
}

/**
 * Check if a given object implements the SystemUsage interface.
 */
export function instanceOfSystemUsage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SystemUsageFromJSON(json: any): SystemUsage {
    return SystemUsageFromJSONTyped(json, false);
}

export function SystemUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemUsage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cpuUsage': !exists(json, 'cpuUsage') ? undefined : CpuUsageFromJSON(json['cpuUsage']),
        'memUsage': !exists(json, 'memUsage') ? undefined : MemUsageFromJSON(json['memUsage']),
        'networkAdapterUsage': !exists(json, 'networkAdapterUsage') ? undefined : ((json['networkAdapterUsage'] as Array<any>).map(NetworkAdapterUsageFromJSON)),
        'disk': !exists(json, 'disk') ? undefined : (mapValues(json['disk'], DiskFromJSON)),
    };
}

export function SystemUsageToJSON(value?: SystemUsage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cpuUsage': CpuUsageToJSON(value.cpuUsage),
        'memUsage': MemUsageToJSON(value.memUsage),
        'networkAdapterUsage': value.networkAdapterUsage === undefined ? undefined : ((value.networkAdapterUsage as Array<any>).map(NetworkAdapterUsageToJSON)),
        'disk': value.disk === undefined ? undefined : (mapValues(value.disk, DiskToJSON)),
    };
}

