/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Throughput
 */
export interface Throughput {
    /**
     * 
     * @type {number}
     * @memberof Throughput
     */
    readRateBytesPerSecond: number | null;
    /**
     * 
     * @type {number}
     * @memberof Throughput
     */
    writeRateBytesPerSecond: number | null;
}

/**
 * Check if a given object implements the Throughput interface.
 */
export function instanceOfThroughput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "readRateBytesPerSecond" in value;
    isInstance = isInstance && "writeRateBytesPerSecond" in value;

    return isInstance;
}

export function ThroughputFromJSON(json: any): Throughput {
    return ThroughputFromJSONTyped(json, false);
}

export function ThroughputFromJSONTyped(json: any, ignoreDiscriminator: boolean): Throughput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'readRateBytesPerSecond': json['readRateBytesPerSecond'],
        'writeRateBytesPerSecond': json['writeRateBytesPerSecond'],
    };
}

export function ThroughputToJSON(value?: Throughput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'readRateBytesPerSecond': value.readRateBytesPerSecond,
        'writeRateBytesPerSecond': value.writeRateBytesPerSecond,
    };
}

