/* tslint:disable */
/* eslint-disable */
/**
 * VitalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ManagedModelDto } from './ManagedModelDto';
import {
    ManagedModelDtoFromJSON,
    ManagedModelDtoFromJSONTyped,
    ManagedModelDtoToJSON,
} from './ManagedModelDto';

/**
 * 
 * @export
 * @interface UpdateManagedRequest
 */
export interface UpdateManagedRequest {
    /**
     * 
     * @type {ManagedModelDto}
     * @memberof UpdateManagedRequest
     */
    managedModelDto: ManagedModelDto;
}

/**
 * Check if a given object implements the UpdateManagedRequest interface.
 */
export function instanceOfUpdateManagedRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "managedModelDto" in value;

    return isInstance;
}

export function UpdateManagedRequestFromJSON(json: any): UpdateManagedRequest {
    return UpdateManagedRequestFromJSONTyped(json, false);
}

export function UpdateManagedRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateManagedRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'managedModelDto': ManagedModelDtoFromJSON(json['managedModelDto']),
    };
}

export function UpdateManagedRequestToJSON(value?: UpdateManagedRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'managedModelDto': ManagedModelDtoToJSON(value.managedModelDto),
    };
}

