name: Generate update meta on release publish

on:
  release:
    types: [published]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.2.1
      with:
        version: 7.5.0
        run_install: false
    - name: run script
      run: |
        cd "./Source"
        pnpm i -g ts-node
        pnpm i -D @types/node
        pnpm i
        pnpm run GenerateUpdateMeta -t ${{ github.ref_name }} -o ../latest_update_meta.json
    - name: commit and push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update latest update meta
        branch: master
