name: Web App Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths: 'Source/ClientApp/**'
defaults:
  run:
    working-directory: ./Source/ClientApp
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3       
    - name: Cache pnpm modules
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-
    - uses: pnpm/action-setup@v2.2.1
      with:
        version: 7.5.0
        run_install: false
    - run: pnpm i -g ts-node
    - run: pnpm i -g @types/node
    - run: pnpm i
    - run: pnpm test
    - run: pnpm build
