name: Vital Service Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths: ['Source/Services/VitalService/**', '.github/workflows/vital-service-tests.yml']
jobs:
  build:
    runs-on: [windows-latest, macos-latest]
    env: 
       source: ./Source/Services/VitalService
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
    - uses: actions/checkout@v3       
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.*
        include-prerelease: false
    - name: Install dependencies
      run: dotnet restore ${{env.source}}
    - name: Restore dotnet tools
      run: cd ${{env.source}} && dotnet tool restore 
    - name: Build
      run: dotnet build ${{env.source}} -c release
    - name: Test
      run: dotnet test ${{env.source}}
    
