name: Vital Service Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths: ['Source/Services/VitalService/**', '.github/workflows/vital-service-tests.yml']
jobs:
  build:
    runs-on: windows-latest
    env: 
       source: ./Source/Services/VitalService
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
    - uses: actions/checkout@v3       
    - name: Cache pnpm modules
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-
    - uses: pnpm/action-setup@v2.2.1
      with:
        version: 6.0.2
        run_install: false
    - run: pnpm i -g ts-node
    - run: pnpm i -g @types/node
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.*
        include-prerelease: false
    - name: Install dependencies
      run: dotnet restore ${{env.source}}
    - name: Restore dotnet tools
      run: cd ${{env.source}} && dotnet tool restore 
    - name: Build
      run: dotnet build ${{env.source}} -c release
    - name: Test
      run: dotnet test ${{env.source}}
    
