version: '3.4'
services:
  influxdb:
    hostname: influxdb
    image: influxdb:2.1.1
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdb2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
  

  # Use the influx cli to set up an influxdb instance. 
volumes:
  influxdb2: